modLoader="javafml"
loaderVersion="[36,)"
license="Mozilla Public License 2.0"

[[mods]]
modId="naruto_shippuden"
version="2.7.0"
displayName="Naruto Shippuden"
credits="Originally created with MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/narutomod https://modrinth.com/mod/naruto-shippuden"
authors="FishyHard, Aqua"

[[dependencies.naruto_shippuden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
