modLoader="javafml"
loaderVersion="[36,)"
license="Mozilla Public License 2.0"

[[mods]]
modId="naruto_shippuden"
version="2.7.0"
displayName="Naruto Shippuden"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/narutomod https://modrinth.com/mod/naruto-shippuden"
authors="FishyHard, Aqua"

[[dependencies.naruto_shippuden]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"


[[dependencies.naruto_shippuden]]
    modId="pehkui"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naruto_shippuden]]
    modId="fishyhard_fhcore"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naruto_shippuden]]
    modId="kleiders_custom_renderer"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.naruto_shippuden]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naruto_shippuden]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naruto_shippuden]]
    modId="fishyhard_fhcore"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naruto_shippuden]]
    modId="kleiders_custom_renderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

