package net.mcreator.narutoshippudenmod;

import net.minecraftforge.fml.network.PacketDistributor;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.event.AttachCapabilitiesEvent;
import net.minecraftforge.common.util.LazyOptional;
import net.minecraftforge.common.util.FakePlayer;
import net.minecraftforge.common.capabilities.ICapabilitySerializable;
import net.minecraftforge.common.capabilities.CapabilityManager;
import net.minecraftforge.common.capabilities.CapabilityInject;
import net.minecraftforge.common.capabilities.Capability;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.Direction;
import net.minecraft.network.PacketBuffer;
import net.minecraft.nbt.INBT;
import net.minecraft.nbt.CompoundNBT;
import net.minecraft.item.ItemStack;
import net.minecraft.entity.player.ServerPlayerEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.entity.Entity;
import net.minecraft.client.Minecraft;

import java.util.function.Supplier;
import java.util.Set;
import java.util.LinkedHashSet;

public class NarutoShippudenModVariables {
	public NarutoShippudenModVariables(NarutoShippudenModElements elements) {
		elements.addNetworkMessage(PlayerVariablesSyncMessage.class, PlayerVariablesSyncMessage::buffer, PlayerVariablesSyncMessage::new,
				PlayerVariablesSyncMessage::handler);
		FMLJavaModLoadingContext.get().getModEventBus().addListener(this::init);
	}

	private void init(FMLCommonSetupEvent event) {
		CapabilityManager.INSTANCE.register(PlayerVariables.class, new PlayerVariablesStorage(), PlayerVariables::new);
	}

	@CapabilityInject(PlayerVariables.class)
	public static Capability<PlayerVariables> PLAYER_VARIABLES_CAPABILITY = null;
	/** Read-only fallback for entities without the capability. Never write to it. */
	private static final PlayerVariables DEFAULTS = new PlayerVariables();

	/** Player variables of the entity, or shared defaults when it has none. Only read from the result. */
	public static PlayerVariables get(Entity entity) {
		return entity.getCapability(PLAYER_VARIABLES_CAPABILITY, null).orElse(DEFAULTS);
	}

	@SubscribeEvent
	public void onAttachCapabilities(AttachCapabilitiesEvent<Entity> event) {
		if (event.getObject() instanceof PlayerEntity && !(event.getObject() instanceof FakePlayer))
			event.addCapability(new ResourceLocation("naruto_shippuden", "player_variables"), new PlayerVariablesProvider());
	}

	private static class PlayerVariablesProvider implements ICapabilitySerializable<INBT> {
		private final LazyOptional<PlayerVariables> instance = LazyOptional.of(PLAYER_VARIABLES_CAPABILITY::getDefaultInstance);

		@Override
		public <T> LazyOptional<T> getCapability(Capability<T> cap, Direction side) {
			return cap == PLAYER_VARIABLES_CAPABILITY ? instance.cast() : LazyOptional.empty();
		}

		@Override
		public INBT serializeNBT() {
			return PLAYER_VARIABLES_CAPABILITY.getStorage().writeNBT(PLAYER_VARIABLES_CAPABILITY, this.instance.orElseThrow(RuntimeException::new),
					null);
		}

		@Override
		public void deserializeNBT(INBT nbt) {
			PLAYER_VARIABLES_CAPABILITY.getStorage().readNBT(PLAYER_VARIABLES_CAPABILITY, this.instance.orElseThrow(RuntimeException::new), null,
					nbt);
		}
	}

	private static final PlayerVariablesStorage STORAGE = new PlayerVariablesStorage();

	private static class PlayerVariablesStorage implements Capability.IStorage<PlayerVariables> {
		@Override
		public INBT writeNBT(Capability<PlayerVariables> capability, PlayerVariables instance, Direction side) {
			CompoundNBT nbt = new CompoundNBT();
			nbt.putDouble("A_Mission", instance.A_Mission);
			nbt.putBoolean("aburamereleaselogic", instance.aburamereleaselogic);
			nbt.putBoolean("akimichireleaselogic", instance.akimichireleaselogic);
			nbt.putBoolean("asumaquest", instance.asumaquest);
			nbt.putDouble("B_Mission", instance.B_Mission);
			nbt.putDouble("BOSSLEVEL", instance.BOSSLEVEL);
			nbt.putDouble("BOSSLEVELMAX", instance.BOSSLEVELMAX);
			nbt.putBoolean("byakugan", instance.byakugan);
			nbt.putBoolean("byakuganactivate", instance.byakuganactivate);
			nbt.putDouble("C_Mission", instance.C_Mission);
			nbt.putDouble("ChakraAmount", instance.ChakraAmount);
			nbt.putDouble("ChakraMax", instance.ChakraMax);
			nbt.putBoolean("chinoikereleaselogic", instance.chinoikereleaselogic);
			nbt.putDouble("D_Mission", instance.D_Mission);
			nbt.putBoolean("deathgod", instance.deathgod);
			nbt.putString("DojutsuSelectResize", instance.DojutsuSelectResize);
			nbt.putDouble("earth_release", instance.earth_release);
			nbt.putDouble("earth_technique", instance.earth_technique);
			nbt.putDouble("earthlearn", instance.earthlearn);
			nbt.putBoolean("earthreleaselogic", instance.earthreleaselogic);
			nbt.putDouble("Eyes_Height", instance.Eyes_Height);
			nbt.putDouble("fire_release", instance.fire_release);
			nbt.putDouble("firelearn", instance.firelearn);
			nbt.putBoolean("firereleaselogic", instance.firereleaselogic);
			nbt.putDouble("firetechnique", instance.firetechnique);
			nbt.putBoolean("fumareleaselogic", instance.fumareleaselogic);
			nbt.putDouble("genjutsu", instance.genjutsu);
			nbt.putBoolean("gentlefist", instance.gentlefist);
			nbt.putBoolean("hatakereleaselogic", instance.hatakereleaselogic);
			nbt.putBoolean("healbite", instance.healbite);
			nbt.putDouble("Health", instance.Health);
			nbt.putDouble("HealthMax", instance.HealthMax);
			nbt.putBoolean("hoshigakireleaselogic", instance.hoshigakireleaselogic);
			nbt.putBoolean("hozukireleaselogic", instance.hozukireleaselogic);
			nbt.putDouble("hyugalearn", instance.hyugalearn);
			nbt.putDouble("hyugarelease", instance.hyugarelease);
			nbt.putBoolean("hyugareleaselogic", instance.hyugareleaselogic);
			nbt.putDouble("hyugatechnique", instance.hyugatechnique);
			nbt.putBoolean("iburireleaselogic", instance.iburireleaselogic);
			nbt.putBoolean("inuzukareleaselogic", instance.inuzukareleaselogic);
			nbt.putDouble("IQ", instance.IQ);
			nbt.putBoolean("izanagi", instance.izanagi);
			nbt.putBoolean("izanagiuse", instance.izanagiuse);
			nbt.putBoolean("izunoreleaselogic", instance.izunoreleaselogic);
			nbt.putBoolean("joinworld", instance.joinworld);
			nbt.putDouble("jp", instance.jp);
			nbt.putDouble("jutsupower", instance.jutsupower);
			nbt.putDouble("jutsupowerstat", instance.jutsupowerstat);
			nbt.putBoolean("kaguyareleaselogic", instance.kaguyareleaselogic);
			nbt.putBoolean("kazekagereleaselogic", instance.kazekagereleaselogic);
			nbt.putDouble("kenjutsu", instance.kenjutsu);
			nbt.putBoolean("ketsuryugan", instance.ketsuryugan);
			nbt.putBoolean("ketsuryuganactivate", instance.ketsuryuganactivate);
			nbt.putDouble("kinjutsu", instance.kinjutsu);
			nbt.putBoolean("kuramareleaselogic", instance.kuramareleaselogic);
			nbt.putBoolean("leereleaselogic", instance.leereleaselogic);
			nbt.putDouble("LEVEL", instance.LEVEL);
			nbt.putDouble("LEVELMAX", instance.LEVELMAX);
			nbt.putDouble("LEVELMAXMINIGAME", instance.LEVELMAXMINIGAME);
			nbt.putDouble("LEVELMINIGAME", instance.LEVELMINIGAME);
			nbt.putDouble("LEVELSTAT", instance.LEVELSTAT);
			nbt.putDouble("LEVELSTATMINIGAME", instance.LEVELSTATMINIGAME);
			nbt.putDouble("lightning_release", instance.lightning_release);
			nbt.putDouble("lightning_technique", instance.lightning_technique);
			nbt.putDouble("lightninglearn", instance.lightninglearn);
			nbt.putBoolean("lightningreleaselogic", instance.lightningreleaselogic);
			nbt.putBoolean("Mangekyou_Sharingan", instance.Mangekyou_Sharingan);
			nbt.putDouble("maxhealth", instance.maxhealth);
			nbt.putDouble("maxspeed", instance.maxspeed);
			nbt.putDouble("medicine", instance.medicine);
			nbt.putDouble("Mini_Game_Timer_Button", instance.Mini_Game_Timer_Button);
			nbt.putBoolean("namikazereleaselogic", instance.namikazereleaselogic);
			nbt.putBoolean("narareleaselogic", instance.narareleaselogic);
			nbt.putDouble("NarutoTimerAwakening", instance.NarutoTimerAwakening);
			nbt.putDouble("ninjutsu", instance.ninjutsu);
			nbt.putBoolean("otsutsukireleaselogic", instance.otsutsukireleaselogic);
			nbt.putDouble("Pupils_Height", instance.Pupils_Height);
			nbt.putString("rank", instance.rank);
			nbt.putDouble("S_Mission", instance.S_Mission);
			nbt.putBoolean("sarutobireleaselogic", instance.sarutobireleaselogic);
			nbt.putDouble("selectclanrelease", instance.selectclanrelease);
			nbt.putDouble("selectnaturerelease", instance.selectnaturerelease);
			nbt.putDouble("selectvillage", instance.selectvillage);
			nbt.putBoolean("senjureleaselogic", instance.senjureleaselogic);
			nbt.putDouble("senjutsu", instance.senjutsu);
			nbt.putDouble("SenjutsuChakraAmount", instance.SenjutsuChakraAmount);
			nbt.putDouble("SenjutsuChakraMax", instance.SenjutsuChakraMax);
			nbt.putBoolean("sharingan", instance.sharingan);
			nbt.putBoolean("sharinganactivate", instance.sharinganactivate);
			nbt.putDouble("sharinganlearn", instance.sharinganlearn);
			nbt.putDouble("sharinganrelease", instance.sharinganrelease);
			nbt.putDouble("sharingantechnique", instance.sharingantechnique);
			nbt.putBoolean("shikamaruquest", instance.shikamaruquest);
			nbt.putBoolean("shimurareleaselogic", instance.shimurareleaselogic);
			nbt.putDouble("Shinobi_Murder_Count", instance.Shinobi_Murder_Count);
			nbt.putDouble("shurikenjutsu", instance.shurikenjutsu);
			nbt.putDouble("smokelearn", instance.smokelearn);
			nbt.putBoolean("smokereleaselogic", instance.smokereleaselogic);
			nbt.putDouble("smoketechnique", instance.smoketechnique);
			nbt.putDouble("sp", instance.sp);
			nbt.putDouble("speed", instance.speed);
			nbt.putDouble("spusecount", instance.spusecount);
			nbt.putDouble("SS_Mission", instance.SS_Mission);
			nbt.putDouble("storymode", instance.storymode);
			nbt.putDouble("summoning", instance.summoning);
			nbt.putDouble("taijutsu", instance.taijutsu);
			nbt.putBoolean("tenroreleaselogic", instance.tenroreleaselogic);
			nbt.putBoolean("tsuchigumoreleaselogic", instance.tsuchigumoreleaselogic);
			nbt.putBoolean("uchihareleaselogic", instance.uchihareleaselogic);
			nbt.putBoolean("uzumakichains", instance.uzumakichains);
			nbt.putDouble("uzumakilearn", instance.uzumakilearn);
			nbt.putDouble("uzumakirelease", instance.uzumakirelease);
			nbt.putBoolean("uzumakireleaselogic", instance.uzumakireleaselogic);
			nbt.putDouble("uzumakitechnique", instance.uzumakitechnique);
			nbt.putString("village", instance.village);
			nbt.putDouble("water_release", instance.water_release);
			nbt.putDouble("water_technique", instance.water_technique);
			nbt.putDouble("waterlearn", instance.waterlearn);
			nbt.putBoolean("waterreleaselogic", instance.waterreleaselogic);
			nbt.putDouble("wind_release", instance.wind_release);
			nbt.putDouble("wind_technique", instance.wind_technique);
			nbt.putDouble("windlearn", instance.windlearn);
			nbt.putBoolean("windreleaselogic", instance.windreleaselogic);
			nbt.putBoolean("yukireleaselogic", instance.yukireleaselogic);
			nbt.putBoolean("smokefist", instance.smokefist);
			nbt.putDouble("smokerelease", instance.smokerelease);
			nbt.putBoolean("Chakra_Control", instance.Chakra_Control);
			nbt.putString("player_name", instance.player_name);
			nbt.putString("customjutsutype", instance.customjutsutype);
			nbt.putString("customjutsuspeed", instance.customjutsuspeed);
			nbt.putString("customjutsurelease", instance.customjutsurelease);
			nbt.putDouble("customjutsuchakra", instance.customjutsuchakra);
			nbt.putDouble("customjutsujpcost", instance.customjutsujpcost);
			nbt.putString("customjutsu1name", instance.customjutsu1name);
			nbt.putBoolean("customjutsucheckpricelogic", instance.customjutsucheckpricelogic);
			nbt.putDouble("customjutsucheckpricefinal", instance.customjutsucheckpricefinal);
			nbt.putBoolean("customjutsujpreadybuy", instance.customjutsujpreadybuy);
			nbt.putBoolean("customjutsufire", instance.customjutsufire);
			nbt.putBoolean("customjutsuwind", instance.customjutsuwind);
			nbt.putBoolean("customjutsulightning", instance.customjutsulightning);
			nbt.putBoolean("customjutsuwater", instance.customjutsuwater);
			nbt.putBoolean("customjutsuearth", instance.customjutsuearth);
			nbt.putString("customjutsutypesave", instance.customjutsutypesave);
			nbt.putString("customjutsuspeedsave", instance.customjutsuspeedsave);
			nbt.putString("customjutsureleasesave", instance.customjutsureleasesave);
			nbt.putDouble("customjutsuchakrasave", instance.customjutsuchakrasave);
			nbt.putString("customjutsutype1save", instance.customjutsutype1save);
			nbt.putString("customjutsuspeed1save", instance.customjutsuspeed1save);
			nbt.putString("customjutsurelease1save", instance.customjutsurelease1save);
			nbt.putDouble("customjutsuchakra1save", instance.customjutsuchakra1save);
			nbt.putString("jutsunamesave", instance.jutsunamesave);
			nbt.putString("jutsunamesave1", instance.jutsunamesave1);
			nbt.putBoolean("customjutsu1learn", instance.customjutsu1learn);
			nbt.putBoolean("isshikidojutsu", instance.isshikidojutsu);
			nbt.putBoolean("isshikidojutsuactivate", instance.isshikidojutsuactivate);
			nbt.putDouble("sukunahikonasize", instance.sukunahikonasize);
			nbt.putDouble("isshikidojutsutechnique", instance.isshikidojutsutechnique);
			nbt.putDouble("isshikidojutsulearn", instance.isshikidojutsulearn);
			nbt.putDouble("isshikidojutsurelease", instance.isshikidojutsurelease);
			nbt.putBoolean("FollowAkamaru", instance.FollowAkamaru);
			nbt.putDouble("inuzukatechnique", instance.inuzukatechnique);
			nbt.putDouble("inuzukalearn", instance.inuzukalearn);
			nbt.putBoolean("mangekyouletter", instance.mangekyouletter);
			nbt.putDouble("magnettechnique", instance.magnettechnique);
			nbt.putBoolean("magnetreleaselogic", instance.magnetreleaselogic);
			nbt.putDouble("magnetlearn", instance.magnetlearn);
			nbt.putBoolean("BoxDeity", instance.BoxDeity);
			nbt.putBoolean("Login_Dojutsu", instance.Login_Dojutsu);
			nbt.putDouble("voltic_technique", instance.voltic_technique);
			nbt.putDouble("volticlearn", instance.volticlearn);
			nbt.putString("DojutsuSelect2", instance.DojutsuSelect2);
			nbt.putString("DojutsuSelect3", instance.DojutsuSelect3);
			nbt.putBoolean("MangekyouSharinganSasuke", instance.MangekyouSharinganSasuke);
			nbt.putBoolean("MangekyouSharinganItachi", instance.MangekyouSharinganItachi);
			nbt.putBoolean("MangekyouSharinganMadara", instance.MangekyouSharinganMadara);
			nbt.putBoolean("MangekyouSharinganObito", instance.MangekyouSharinganObito);
			nbt.putBoolean("MangekyouSharinganShisui", instance.MangekyouSharinganShisui);
			nbt.putBoolean("MangekyouSharinganActivate", instance.MangekyouSharinganActivate);
			nbt.putBoolean("MangekyouSharinganKakashi", instance.MangekyouSharinganKakashi);
			nbt.putBoolean("SharinganKakashi", instance.SharinganKakashi);
			nbt.putDouble("hatakelearn", instance.hatakelearn);
			nbt.putDouble("volticrelease", instance.volticrelease);
			nbt.putBoolean("BoxDojutsuSelect", instance.BoxDojutsuSelect);
			nbt.putBoolean("VolticThomasCannonDamage", instance.VolticThomasCannonDamage);
			nbt.putBoolean("VolticMode", instance.VolticMode);
			nbt.putDouble("magnet_release", instance.magnet_release);
			nbt.putDouble("lee_technique", instance.lee_technique);
			nbt.putDouble("leelearn", instance.leelearn);
			nbt.putDouble("eight_gates", instance.eight_gates);
			nbt.putBoolean("deathgodcooldown", instance.deathgodcooldown);
			nbt.putDouble("iburi_release", instance.iburi_release);
			nbt.putDouble("inuzuka_release", instance.inuzuka_release);
			nbt.putBoolean("akamaru_summon", instance.akamaru_summon);
			nbt.putDouble("kazekage_release", instance.kazekage_release);
			nbt.putBoolean("TheSirMarcus", instance.TheSirMarcus);
			nbt.putDouble("furamingogan_technique", instance.furamingogan_technique);
			nbt.putDouble("furamingoganlearn", instance.furamingoganlearn);
			nbt.putDouble("furamingoganrelease", instance.furamingoganrelease);
			nbt.putBoolean("TheSirMarcusDojutsuSelect", instance.TheSirMarcusDojutsuSelect);
			nbt.putBoolean("Furamingogan", instance.Furamingogan);
			nbt.putBoolean("furamingogan_jump", instance.furamingogan_jump);
			nbt.putDouble("lee_release", instance.lee_release);
			nbt.putDouble("gateslee", instance.gateslee);
			nbt.putBoolean("Gate8", instance.Gate8);
			nbt.putDouble("flyingthundergodkunaicount", instance.flyingthundergodkunaicount);
			nbt.putDouble("flyingthundergodkunaipos1x", instance.flyingthundergodkunaipos1x);
			nbt.putDouble("flyingthundergodkunaipos1y", instance.flyingthundergodkunaipos1y);
			nbt.putDouble("flyingthundergodkunaipos1z", instance.flyingthundergodkunaipos1z);
			nbt.putDouble("flyingthundergodkunaipos2x", instance.flyingthundergodkunaipos2x);
			nbt.putDouble("flyingthundergodkunaipos2y", instance.flyingthundergodkunaipos2y);
			nbt.putDouble("flyingthundergodkunaipos2z", instance.flyingthundergodkunaipos2z);
			nbt.putDouble("flyingthundergodkunaipos3x", instance.flyingthundergodkunaipos3x);
			nbt.putDouble("flyingthundergodkunaipos3y", instance.flyingthundergodkunaipos3y);
			nbt.putDouble("flyingthundergodkunaipos3z", instance.flyingthundergodkunaipos3z);
			nbt.putDouble("flyingthundergodkunaiteleportselect", instance.flyingthundergodkunaiteleportselect);
			nbt.putBoolean("flyingthundergodkunaipos1logic", instance.flyingthundergodkunaipos1logic);
			nbt.putBoolean("flyingthundergodkunaipos2logic", instance.flyingthundergodkunaipos2logic);
			nbt.putBoolean("flyingthundergodkunaipos3logic", instance.flyingthundergodkunaipos3logic);
			nbt.putDouble("flyingthundergodkunaicount1", instance.flyingthundergodkunaicount1);
			nbt.putDouble("flyingthundergodkunaicount2", instance.flyingthundergodkunaicount2);
			nbt.putDouble("dojutsusize", instance.dojutsusize);
			nbt.putString("dojutsubyakugan", instance.dojutsubyakugan);
			nbt.putString("dojutsusharingan", instance.dojutsusharingan);
			nbt.putString("dojutsuketsuryugan", instance.dojutsuketsuryugan);
			nbt.putString("dojutsums", instance.dojutsums);
			nbt.putString("dojutsuisshiki", instance.dojutsuisshiki);
			nbt.putBoolean("PassingFang", instance.PassingFang);
			nbt.putDouble("stormtechnique", instance.stormtechnique);
			nbt.putBoolean("stormreleaselogic", instance.stormreleaselogic);
			nbt.putDouble("stormlearn", instance.stormlearn);
			nbt.putDouble("storm_release", instance.storm_release);
			nbt.putBoolean("stormlaser", instance.stormlaser);
			nbt.putDouble("namikaze_release", instance.namikaze_release);
			nbt.putDouble("otsutsuki_release", instance.otsutsuki_release);
			nbt.putDouble("otsutsuki_tool", instance.otsutsuki_tool);
			nbt.putString("dojutsurinnegan", instance.dojutsurinnegan);
			nbt.putString("dojutsutenseigan", instance.dojutsutenseigan);
			nbt.putBoolean("tenseigan", instance.tenseigan);
			nbt.putBoolean("tenseiganactivate", instance.tenseiganactivate);
			nbt.putBoolean("rinnegan", instance.rinnegan);
			nbt.putBoolean("rinneganactivate", instance.rinneganactivate);
			nbt.putDouble("otsutsuki_path", instance.otsutsuki_path);
			nbt.putBoolean("woodreleaselogic", instance.woodreleaselogic);
			nbt.putDouble("woodtechnique", instance.woodtechnique);
			nbt.putDouble("woodlearn", instance.woodlearn);
			nbt.putDouble("wood_release", instance.wood_release);
			nbt.putBoolean("otsutsuki_mangekyou", instance.otsutsuki_mangekyou);
			nbt.putDouble("senju_release", instance.senju_release);
			nbt.putBoolean("icereleaselogic", instance.icereleaselogic);
			nbt.putDouble("icetechnique", instance.icetechnique);
			nbt.putDouble("icelearn", instance.icelearn);
			nbt.putDouble("ice_release", instance.ice_release);
			nbt.putBoolean("ice_mirror", instance.ice_mirror);
			nbt.putDouble("yuki_release", instance.yuki_release);
			nbt.putDouble("tenro_release", instance.tenro_release);
			nbt.putDouble("tenrolearn", instance.tenrolearn);
			nbt.putDouble("tenrotechnique", instance.tenrotechnique);
			nbt.putBoolean("tenromode", instance.tenromode);
			nbt.putDouble("izuno_release", instance.izuno_release);
			nbt.putDouble("izunolearn", instance.izunolearn);
			nbt.putDouble("izunotechnique", instance.izunotechnique);
			nbt.putBoolean("izunochakramode", instance.izunochakramode);
			nbt.putBoolean("izunocat", instance.izunocat);
			nbt.putDouble("calendar_calculator", instance.calendar_calculator);
			nbt.putDouble("gift", instance.gift);
			nbt.putDouble("giftcount", instance.giftcount);
			nbt.putBoolean("christmas2022", instance.christmas2022);
			nbt.putBoolean("shimura_active", instance.shimura_active);
			nbt.putBoolean("SharinganShimura", instance.SharinganShimura);
			nbt.putDouble("aburametechnique", instance.aburametechnique);
			nbt.putDouble("aburamelearn", instance.aburamelearn);
			nbt.putDouble("aburame_release", instance.aburame_release);
			nbt.putDouble("sarutobitechnique", instance.sarutobitechnique);
			nbt.putDouble("sarutobilearn", instance.sarutobilearn);
			nbt.putDouble("sarutobirelease", instance.sarutobirelease);
			nbt.putDouble("hozukitechnique", instance.hozukitechnique);
			nbt.putDouble("hozukilearn", instance.hozukilearn);
			nbt.putDouble("hozukirelease", instance.hozukirelease);
			nbt.putDouble("tsuchigumotechnique", instance.tsuchigumotechnique);
			nbt.putDouble("tsuchigumolearn", instance.tsuchigumolearn);
			nbt.putDouble("tsuchigumorelease", instance.tsuchigumorelease);
			nbt.putBoolean("waterblob", instance.waterblob);
			nbt.putBoolean("Great_Water_Arm", instance.Great_Water_Arm);
			nbt.putBoolean("bonereleaselogic", instance.bonereleaselogic);
			nbt.putDouble("bonetechnique", instance.bonetechnique);
			nbt.putDouble("bonelearn", instance.bonelearn);
			nbt.putDouble("bone_release", instance.bone_release);
			nbt.putBoolean("DanceOfTheLarch", instance.DanceOfTheLarch);
			nbt.putDouble("kaguya_release", instance.kaguya_release);
			nbt.putDouble("hoshigaki_release", instance.hoshigaki_release);
			nbt.putDouble("fumatechnique", instance.fumatechnique);
			nbt.putDouble("fumalearn", instance.fumalearn);
			nbt.putDouble("fumarelease", instance.fumarelease);
			nbt.putDouble("magnet_coat", instance.magnet_coat);
			nbt.putDouble("Shadow1X", instance.Shadow1X);
			nbt.putDouble("Shadow2X", instance.Shadow2X);
			nbt.putDouble("Shadow1Z", instance.Shadow1Z);
			nbt.putDouble("Shadow2Z", instance.Shadow2Z);
			nbt.putBoolean("NaraClanShadow", instance.NaraClanShadow);
			nbt.putDouble("OriginalZ1", instance.OriginalZ1);
			nbt.putDouble("OriginalX1", instance.OriginalX1);
			nbt.putBoolean("EightTrigramsPalmsRevolvingHeaven", instance.EightTrigramsPalmsRevolvingHeaven);
			nbt.putBoolean("InsectJarTechnique", instance.InsectJarTechnique);
			nbt.putDouble("ShadowX1", instance.ShadowX1);
			nbt.putDouble("ShadowX2", instance.ShadowX2);
			nbt.putDouble("ShadowZ1", instance.ShadowZ1);
			nbt.putDouble("ShadowZ2", instance.ShadowZ2);
			nbt.putDouble("akimichitechnique", instance.akimichitechnique);
			nbt.putDouble("akimichilearn", instance.akimichilearn);
			nbt.putDouble("akimichirelease", instance.akimichirelease);
			nbt.putDouble("caloriecontrol", instance.caloriecontrol);
			nbt.putBoolean("HumanBulletTank", instance.HumanBulletTank);
			nbt.putBoolean("ButterflyMode", instance.ButterflyMode);
			nbt.putBoolean("SpikedHumanBulletTank", instance.SpikedHumanBulletTank);
			nbt.putDouble("zombiekillcount", instance.zombiekillcount);
			nbt.putDouble("pillagerkillcount", instance.pillagerkillcount);
			nbt.putDouble("typhoontechnique", instance.typhoontechnique);
			nbt.putDouble("typhoonlearn", instance.typhoonlearn);
			nbt.putDouble("typhoonrelease", instance.typhoonrelease);
			nbt.putBoolean("typhoonreleaslogic", instance.typhoonreleaslogic);
			nbt.putDouble("swiftlearn", instance.swiftlearn);
			nbt.putDouble("swiftrelease", instance.swiftrelease);
			nbt.putBoolean("swiftreleaselogic", instance.swiftreleaselogic);
			nbt.putDouble("steeltechnique", instance.steeltechnique);
			nbt.putDouble("steellearn", instance.steellearn);
			nbt.putDouble("steelrelease", instance.steelrelease);
			nbt.putBoolean("steelreleaselogic", instance.steelreleaselogic);
			nbt.putDouble("dusttechnique", instance.dusttechnique);
			nbt.putDouble("dustlearn", instance.dustlearn);
			nbt.putDouble("dustrelease", instance.dustrelease);
			nbt.putBoolean("dustreleaselogic", instance.dustreleaselogic);
			nbt.putDouble("boiltechnique", instance.boiltechnique);
			nbt.putDouble("boillearn", instance.boillearn);
			nbt.putDouble("boilrelease", instance.boilrelease);
			nbt.putBoolean("boilreleaselogic", instance.boilreleaselogic);
			nbt.putBoolean("swiftmode", instance.swiftmode);
			nbt.putBoolean("UnrivaledStrength", instance.UnrivaledStrength);
			nbt.putBoolean("ImperviousArmor", instance.ImperviousArmor);
			nbt.putBoolean("WindMode", instance.WindMode);
			nbt.putBoolean("SmokeForm", instance.SmokeForm);
			nbt.putString("ButterFlyModeColor", instance.ButterFlyModeColor);
			nbt.putDouble("HPBarfill", instance.HPBarfill);
			nbt.putDouble("ChakraBarfill", instance.ChakraBarfill);
			nbt.putBoolean("DashCooldown", instance.DashCooldown);
			nbt.putDouble("DashCooldownTicks", instance.DashCooldownTicks);
			nbt.putDouble("WPressed", instance.WPressed);
			nbt.putDouble("APressed", instance.APressed);
			nbt.putDouble("DPressed", instance.DPressed);
			nbt.putDouble("SPressed", instance.SPressed);
			nbt.putDouble("SpacePressed", instance.SpacePressed);
			nbt.putBoolean("UpDashCooldown", instance.UpDashCooldown);
			nbt.putDouble("UpDashCooldownTicks", instance.UpDashCooldownTicks);
			nbt.putBoolean("SpaceHold", instance.SpaceHold);
			nbt.putBoolean("Dash", instance.Dash);
			nbt.putDouble("DashReset", instance.DashReset);
			nbt.putBoolean("WHold", instance.WHold);
			nbt.putBoolean("WaterWalk", instance.WaterWalk);
			nbt.putBoolean("WallClimb", instance.WallClimb);
			nbt.putDouble("SusanoActive", instance.SusanoActive);
			nbt.putDouble("SusanoForms", instance.SusanoForms);
			nbt.putDouble("StorymodeCooldown", instance.StorymodeCooldown);
			nbt.putString("directionstorymode", instance.directionstorymode);
			nbt.putDouble("TrainingDummyHits", instance.TrainingDummyHits);
			nbt.putString("StoryModeGeninFight", instance.StoryModeGeninFight);
			nbt.putDouble("HeadbandSelect", instance.HeadbandSelect);
			nbt.putBoolean("Kagutsuchi", instance.Kagutsuchi);
			nbt.putBoolean("AmaterasuSusano", instance.AmaterasuSusano);
			nbt.putDouble("MangekyouSharinganRelease", instance.MangekyouSharinganRelease);
			nbt.putDouble("mangekyousharingansasukeamaterasurelease", instance.mangekyousharingansasukeamaterasurelease);
			nbt.putDouble("mangekyousharingansasukeamaterasulearn", instance.mangekyousharingansasukeamaterasulearn);
			nbt.putDouble("mangekyousharingansasukeamaterasutechnique", instance.mangekyousharingansasukeamaterasutechnique);
			nbt.putDouble("mangekyousharingansasukesusanorelease", instance.mangekyousharingansasukesusanorelease);
			nbt.putDouble("mangekyousharingansasukesusanolearn", instance.mangekyousharingansasukesusanolearn);
			nbt.putDouble("mangekyousharingansusanostage", instance.mangekyousharingansusanostage);
			nbt.putDouble("mangekyoushrainganitachiamaterasulearn", instance.mangekyoushrainganitachiamaterasulearn);
			nbt.putDouble("mangekyoushrainganitachisusanorelease", instance.mangekyoushrainganitachisusanorelease);
			nbt.putDouble("mangekyoushrainganitachisusanolearn", instance.mangekyoushrainganitachisusanolearn);
			nbt.putDouble("mangekyousharingankakashikamuilearn", instance.mangekyousharingankakashikamuilearn);
			nbt.putDouble("mangekyousharinganobitokamuirelease", instance.mangekyousharinganobitokamuirelease);
			nbt.putDouble("mangekyousharinganobitokamuilearn", instance.mangekyousharinganobitokamuilearn);
			nbt.putDouble("mangekyousharinganobitokamuitechnique", instance.mangekyousharinganobitokamuitechnique);
			nbt.putDouble("mangekyousharinganobitosusanorelease", instance.mangekyousharinganobitosusanorelease);
			nbt.putDouble("mangekyousharinganobitosusanolearn", instance.mangekyousharinganobitosusanolearn);
			nbt.putBoolean("KamuiPhantomPhase", instance.KamuiPhantomPhase);
			nbt.putBoolean("Eternal_Mangekyou_Sharingan", instance.Eternal_Mangekyou_Sharingan);
			nbt.putBoolean("Eternal_Mangekyou_Sharingan_Sasuke", instance.Eternal_Mangekyou_Sharingan_Sasuke);
			nbt.putBoolean("Eternal_Mangekyou_Sharingan_Madara", instance.Eternal_Mangekyou_Sharingan_Madara);
			nbt.putDouble("Mangekyou_Sharingan_Technique_Use", instance.Mangekyou_Sharingan_Technique_Use);
			nbt.putDouble("Mangekyou_Sharingan_Technique_Use_Max", instance.Mangekyou_Sharingan_Technique_Use_Max);
			nbt.putDouble("mangekyousharinganmadarasusanorelease", instance.mangekyousharinganmadarasusanorelease);
			nbt.putDouble("mangekyousharinganmadarasusanolearn", instance.mangekyousharinganmadarasusanolearn);
			nbt.putDouble("mangekyousharinganshisuisusanorelease", instance.mangekyousharinganshisuisusanorelease);
			nbt.putDouble("mangekyousharinganshisuisusanolearn", instance.mangekyousharinganshisuisusanolearn);
			nbt.putString("genjutsueffect", instance.genjutsueffect);
			nbt.putDouble("samehadamode", instance.samehadamode);
			nbt.put("gunbaicopy", instance.gunbaicopy.write(new CompoundNBT()));
			nbt.putDouble("LevelStatMaxChange", instance.LevelStatMaxChange);
			nbt.putDouble("inuzuka_mode", instance.inuzuka_mode);
			return nbt;
		}

		@Override
		public void readNBT(Capability<PlayerVariables> capability, PlayerVariables instance, Direction side, INBT inbt) {
			CompoundNBT nbt = (CompoundNBT) inbt;
			instance.A_Mission = nbt.getDouble("A_Mission");
			instance.aburamereleaselogic = nbt.getBoolean("aburamereleaselogic");
			instance.akimichireleaselogic = nbt.getBoolean("akimichireleaselogic");
			instance.asumaquest = nbt.getBoolean("asumaquest");
			instance.B_Mission = nbt.getDouble("B_Mission");
			instance.BOSSLEVEL = nbt.getDouble("BOSSLEVEL");
			instance.BOSSLEVELMAX = nbt.getDouble("BOSSLEVELMAX");
			instance.byakugan = nbt.getBoolean("byakugan");
			instance.byakuganactivate = nbt.getBoolean("byakuganactivate");
			instance.C_Mission = nbt.getDouble("C_Mission");
			instance.ChakraAmount = nbt.getDouble("ChakraAmount");
			instance.ChakraMax = nbt.getDouble("ChakraMax");
			instance.chinoikereleaselogic = nbt.getBoolean("chinoikereleaselogic");
			instance.D_Mission = nbt.getDouble("D_Mission");
			instance.deathgod = nbt.getBoolean("deathgod");
			instance.DojutsuSelectResize = nbt.getString("DojutsuSelectResize");
			instance.earth_release = nbt.getDouble("earth_release");
			instance.earth_technique = nbt.getDouble("earth_technique");
			instance.earthlearn = nbt.getDouble("earthlearn");
			instance.earthreleaselogic = nbt.getBoolean("earthreleaselogic");
			instance.Eyes_Height = nbt.getDouble("Eyes_Height");
			instance.fire_release = nbt.getDouble("fire_release");
			instance.firelearn = nbt.getDouble("firelearn");
			instance.firereleaselogic = nbt.getBoolean("firereleaselogic");
			instance.firetechnique = nbt.getDouble("firetechnique");
			instance.fumareleaselogic = nbt.getBoolean("fumareleaselogic");
			instance.genjutsu = nbt.getDouble("genjutsu");
			instance.gentlefist = nbt.getBoolean("gentlefist");
			instance.hatakereleaselogic = nbt.getBoolean("hatakereleaselogic");
			instance.healbite = nbt.getBoolean("healbite");
			instance.Health = nbt.getDouble("Health");
			instance.HealthMax = nbt.getDouble("HealthMax");
			instance.hoshigakireleaselogic = nbt.getBoolean("hoshigakireleaselogic");
			instance.hozukireleaselogic = nbt.getBoolean("hozukireleaselogic");
			instance.hyugalearn = nbt.getDouble("hyugalearn");
			instance.hyugarelease = nbt.getDouble("hyugarelease");
			instance.hyugareleaselogic = nbt.getBoolean("hyugareleaselogic");
			instance.hyugatechnique = nbt.getDouble("hyugatechnique");
			instance.iburireleaselogic = nbt.getBoolean("iburireleaselogic");
			instance.inuzukareleaselogic = nbt.getBoolean("inuzukareleaselogic");
			instance.IQ = nbt.getDouble("IQ");
			instance.izanagi = nbt.getBoolean("izanagi");
			instance.izanagiuse = nbt.getBoolean("izanagiuse");
			instance.izunoreleaselogic = nbt.getBoolean("izunoreleaselogic");
			instance.joinworld = nbt.getBoolean("joinworld");
			instance.jp = nbt.getDouble("jp");
			instance.jutsupower = nbt.getDouble("jutsupower");
			instance.jutsupowerstat = nbt.getDouble("jutsupowerstat");
			instance.kaguyareleaselogic = nbt.getBoolean("kaguyareleaselogic");
			instance.kazekagereleaselogic = nbt.getBoolean("kazekagereleaselogic");
			instance.kenjutsu = nbt.getDouble("kenjutsu");
			instance.ketsuryugan = nbt.getBoolean("ketsuryugan");
			instance.ketsuryuganactivate = nbt.getBoolean("ketsuryuganactivate");
			instance.kinjutsu = nbt.getDouble("kinjutsu");
			instance.kuramareleaselogic = nbt.getBoolean("kuramareleaselogic");
			instance.leereleaselogic = nbt.getBoolean("leereleaselogic");
			instance.LEVEL = nbt.getDouble("LEVEL");
			instance.LEVELMAX = nbt.getDouble("LEVELMAX");
			instance.LEVELMAXMINIGAME = nbt.getDouble("LEVELMAXMINIGAME");
			instance.LEVELMINIGAME = nbt.getDouble("LEVELMINIGAME");
			instance.LEVELSTAT = nbt.getDouble("LEVELSTAT");
			instance.LEVELSTATMINIGAME = nbt.getDouble("LEVELSTATMINIGAME");
			instance.lightning_release = nbt.getDouble("lightning_release");
			instance.lightning_technique = nbt.getDouble("lightning_technique");
			instance.lightninglearn = nbt.getDouble("lightninglearn");
			instance.lightningreleaselogic = nbt.getBoolean("lightningreleaselogic");
			instance.Mangekyou_Sharingan = nbt.getBoolean("Mangekyou_Sharingan");
			instance.maxhealth = nbt.getDouble("maxhealth");
			instance.maxspeed = nbt.getDouble("maxspeed");
			instance.medicine = nbt.getDouble("medicine");
			instance.Mini_Game_Timer_Button = nbt.getDouble("Mini_Game_Timer_Button");
			instance.namikazereleaselogic = nbt.getBoolean("namikazereleaselogic");
			instance.narareleaselogic = nbt.getBoolean("narareleaselogic");
			instance.NarutoTimerAwakening = nbt.getDouble("NarutoTimerAwakening");
			instance.ninjutsu = nbt.getDouble("ninjutsu");
			instance.otsutsukireleaselogic = nbt.getBoolean("otsutsukireleaselogic");
			instance.Pupils_Height = nbt.getDouble("Pupils_Height");
			instance.rank = nbt.getString("rank");
			instance.S_Mission = nbt.getDouble("S_Mission");
			instance.sarutobireleaselogic = nbt.getBoolean("sarutobireleaselogic");
			instance.selectclanrelease = nbt.getDouble("selectclanrelease");
			instance.selectnaturerelease = nbt.getDouble("selectnaturerelease");
			instance.selectvillage = nbt.getDouble("selectvillage");
			instance.senjureleaselogic = nbt.getBoolean("senjureleaselogic");
			instance.senjutsu = nbt.getDouble("senjutsu");
			instance.SenjutsuChakraAmount = nbt.getDouble("SenjutsuChakraAmount");
			instance.SenjutsuChakraMax = nbt.getDouble("SenjutsuChakraMax");
			instance.sharingan = nbt.getBoolean("sharingan");
			instance.sharinganactivate = nbt.getBoolean("sharinganactivate");
			instance.sharinganlearn = nbt.getDouble("sharinganlearn");
			instance.sharinganrelease = nbt.getDouble("sharinganrelease");
			instance.sharingantechnique = nbt.getDouble("sharingantechnique");
			instance.shikamaruquest = nbt.getBoolean("shikamaruquest");
			instance.shimurareleaselogic = nbt.getBoolean("shimurareleaselogic");
			instance.Shinobi_Murder_Count = nbt.getDouble("Shinobi_Murder_Count");
			instance.shurikenjutsu = nbt.getDouble("shurikenjutsu");
			instance.smokelearn = nbt.getDouble("smokelearn");
			instance.smokereleaselogic = nbt.getBoolean("smokereleaselogic");
			instance.smoketechnique = nbt.getDouble("smoketechnique");
			instance.sp = nbt.getDouble("sp");
			instance.speed = nbt.getDouble("speed");
			instance.spusecount = nbt.getDouble("spusecount");
			instance.SS_Mission = nbt.getDouble("SS_Mission");
			instance.storymode = nbt.getDouble("storymode");
			instance.summoning = nbt.getDouble("summoning");
			instance.taijutsu = nbt.getDouble("taijutsu");
			instance.tenroreleaselogic = nbt.getBoolean("tenroreleaselogic");
			instance.tsuchigumoreleaselogic = nbt.getBoolean("tsuchigumoreleaselogic");
			instance.uchihareleaselogic = nbt.getBoolean("uchihareleaselogic");
			instance.uzumakichains = nbt.getBoolean("uzumakichains");
			instance.uzumakilearn = nbt.getDouble("uzumakilearn");
			instance.uzumakirelease = nbt.getDouble("uzumakirelease");
			instance.uzumakireleaselogic = nbt.getBoolean("uzumakireleaselogic");
			instance.uzumakitechnique = nbt.getDouble("uzumakitechnique");
			instance.village = nbt.getString("village");
			instance.water_release = nbt.getDouble("water_release");
			instance.water_technique = nbt.getDouble("water_technique");
			instance.waterlearn = nbt.getDouble("waterlearn");
			instance.waterreleaselogic = nbt.getBoolean("waterreleaselogic");
			instance.wind_release = nbt.getDouble("wind_release");
			instance.wind_technique = nbt.getDouble("wind_technique");
			instance.windlearn = nbt.getDouble("windlearn");
			instance.windreleaselogic = nbt.getBoolean("windreleaselogic");
			instance.yukireleaselogic = nbt.getBoolean("yukireleaselogic");
			instance.smokefist = nbt.getBoolean("smokefist");
			instance.smokerelease = nbt.getDouble("smokerelease");
			instance.Chakra_Control = nbt.getBoolean("Chakra_Control");
			instance.player_name = nbt.getString("player_name");
			instance.customjutsutype = nbt.getString("customjutsutype");
			instance.customjutsuspeed = nbt.getString("customjutsuspeed");
			instance.customjutsurelease = nbt.getString("customjutsurelease");
			instance.customjutsuchakra = nbt.getDouble("customjutsuchakra");
			instance.customjutsujpcost = nbt.getDouble("customjutsujpcost");
			instance.customjutsu1name = nbt.getString("customjutsu1name");
			instance.customjutsucheckpricelogic = nbt.getBoolean("customjutsucheckpricelogic");
			instance.customjutsucheckpricefinal = nbt.getDouble("customjutsucheckpricefinal");
			instance.customjutsujpreadybuy = nbt.getBoolean("customjutsujpreadybuy");
			instance.customjutsufire = nbt.getBoolean("customjutsufire");
			instance.customjutsuwind = nbt.getBoolean("customjutsuwind");
			instance.customjutsulightning = nbt.getBoolean("customjutsulightning");
			instance.customjutsuwater = nbt.getBoolean("customjutsuwater");
			instance.customjutsuearth = nbt.getBoolean("customjutsuearth");
			instance.customjutsutypesave = nbt.getString("customjutsutypesave");
			instance.customjutsuspeedsave = nbt.getString("customjutsuspeedsave");
			instance.customjutsureleasesave = nbt.getString("customjutsureleasesave");
			instance.customjutsuchakrasave = nbt.getDouble("customjutsuchakrasave");
			instance.customjutsutype1save = nbt.getString("customjutsutype1save");
			instance.customjutsuspeed1save = nbt.getString("customjutsuspeed1save");
			instance.customjutsurelease1save = nbt.getString("customjutsurelease1save");
			instance.customjutsuchakra1save = nbt.getDouble("customjutsuchakra1save");
			instance.jutsunamesave = nbt.getString("jutsunamesave");
			instance.jutsunamesave1 = nbt.getString("jutsunamesave1");
			instance.customjutsu1learn = nbt.getBoolean("customjutsu1learn");
			instance.isshikidojutsu = nbt.getBoolean("isshikidojutsu");
			instance.isshikidojutsuactivate = nbt.getBoolean("isshikidojutsuactivate");
			instance.sukunahikonasize = nbt.getDouble("sukunahikonasize");
			instance.isshikidojutsutechnique = nbt.getDouble("isshikidojutsutechnique");
			instance.isshikidojutsulearn = nbt.getDouble("isshikidojutsulearn");
			instance.isshikidojutsurelease = nbt.getDouble("isshikidojutsurelease");
			instance.FollowAkamaru = nbt.getBoolean("FollowAkamaru");
			instance.inuzukatechnique = nbt.getDouble("inuzukatechnique");
			instance.inuzukalearn = nbt.getDouble("inuzukalearn");
			instance.mangekyouletter = nbt.getBoolean("mangekyouletter");
			instance.magnettechnique = nbt.getDouble("magnettechnique");
			instance.magnetreleaselogic = nbt.getBoolean("magnetreleaselogic");
			instance.magnetlearn = nbt.getDouble("magnetlearn");
			instance.BoxDeity = nbt.getBoolean("BoxDeity");
			instance.Login_Dojutsu = nbt.getBoolean("Login_Dojutsu");
			instance.voltic_technique = nbt.getDouble("voltic_technique");
			instance.volticlearn = nbt.getDouble("volticlearn");
			instance.DojutsuSelect2 = nbt.getString("DojutsuSelect2");
			instance.DojutsuSelect3 = nbt.getString("DojutsuSelect3");
			instance.MangekyouSharinganSasuke = nbt.getBoolean("MangekyouSharinganSasuke");
			instance.MangekyouSharinganItachi = nbt.getBoolean("MangekyouSharinganItachi");
			instance.MangekyouSharinganMadara = nbt.getBoolean("MangekyouSharinganMadara");
			instance.MangekyouSharinganObito = nbt.getBoolean("MangekyouSharinganObito");
			instance.MangekyouSharinganShisui = nbt.getBoolean("MangekyouSharinganShisui");
			instance.MangekyouSharinganActivate = nbt.getBoolean("MangekyouSharinganActivate");
			instance.MangekyouSharinganKakashi = nbt.getBoolean("MangekyouSharinganKakashi");
			instance.SharinganKakashi = nbt.getBoolean("SharinganKakashi");
			instance.hatakelearn = nbt.getDouble("hatakelearn");
			instance.volticrelease = nbt.getDouble("volticrelease");
			instance.BoxDojutsuSelect = nbt.getBoolean("BoxDojutsuSelect");
			instance.VolticThomasCannonDamage = nbt.getBoolean("VolticThomasCannonDamage");
			instance.VolticMode = nbt.getBoolean("VolticMode");
			instance.magnet_release = nbt.getDouble("magnet_release");
			instance.lee_technique = nbt.getDouble("lee_technique");
			instance.leelearn = nbt.getDouble("leelearn");
			instance.eight_gates = nbt.getDouble("eight_gates");
			instance.deathgodcooldown = nbt.getBoolean("deathgodcooldown");
			instance.iburi_release = nbt.getDouble("iburi_release");
			instance.inuzuka_release = nbt.getDouble("inuzuka_release");
			instance.akamaru_summon = nbt.getBoolean("akamaru_summon");
			instance.kazekage_release = nbt.getDouble("kazekage_release");
			instance.TheSirMarcus = nbt.getBoolean("TheSirMarcus");
			instance.furamingogan_technique = nbt.getDouble("furamingogan_technique");
			instance.furamingoganlearn = nbt.getDouble("furamingoganlearn");
			instance.furamingoganrelease = nbt.getDouble("furamingoganrelease");
			instance.TheSirMarcusDojutsuSelect = nbt.getBoolean("TheSirMarcusDojutsuSelect");
			instance.Furamingogan = nbt.getBoolean("Furamingogan");
			instance.furamingogan_jump = nbt.getBoolean("furamingogan_jump");
			instance.lee_release = nbt.getDouble("lee_release");
			instance.gateslee = nbt.getDouble("gateslee");
			instance.Gate8 = nbt.getBoolean("Gate8");
			instance.flyingthundergodkunaicount = nbt.getDouble("flyingthundergodkunaicount");
			instance.flyingthundergodkunaipos1x = nbt.getDouble("flyingthundergodkunaipos1x");
			instance.flyingthundergodkunaipos1y = nbt.getDouble("flyingthundergodkunaipos1y");
			instance.flyingthundergodkunaipos1z = nbt.getDouble("flyingthundergodkunaipos1z");
			instance.flyingthundergodkunaipos2x = nbt.getDouble("flyingthundergodkunaipos2x");
			instance.flyingthundergodkunaipos2y = nbt.getDouble("flyingthundergodkunaipos2y");
			instance.flyingthundergodkunaipos2z = nbt.getDouble("flyingthundergodkunaipos2z");
			instance.flyingthundergodkunaipos3x = nbt.getDouble("flyingthundergodkunaipos3x");
			instance.flyingthundergodkunaipos3y = nbt.getDouble("flyingthundergodkunaipos3y");
			instance.flyingthundergodkunaipos3z = nbt.getDouble("flyingthundergodkunaipos3z");
			instance.flyingthundergodkunaiteleportselect = nbt.getDouble("flyingthundergodkunaiteleportselect");
			instance.flyingthundergodkunaipos1logic = nbt.getBoolean("flyingthundergodkunaipos1logic");
			instance.flyingthundergodkunaipos2logic = nbt.getBoolean("flyingthundergodkunaipos2logic");
			instance.flyingthundergodkunaipos3logic = nbt.getBoolean("flyingthundergodkunaipos3logic");
			instance.flyingthundergodkunaicount1 = nbt.getDouble("flyingthundergodkunaicount1");
			instance.flyingthundergodkunaicount2 = nbt.getDouble("flyingthundergodkunaicount2");
			instance.dojutsusize = nbt.getDouble("dojutsusize");
			instance.dojutsubyakugan = nbt.getString("dojutsubyakugan");
			instance.dojutsusharingan = nbt.getString("dojutsusharingan");
			instance.dojutsuketsuryugan = nbt.getString("dojutsuketsuryugan");
			instance.dojutsums = nbt.getString("dojutsums");
			instance.dojutsuisshiki = nbt.getString("dojutsuisshiki");
			instance.PassingFang = nbt.getBoolean("PassingFang");
			instance.stormtechnique = nbt.getDouble("stormtechnique");
			instance.stormreleaselogic = nbt.getBoolean("stormreleaselogic");
			instance.stormlearn = nbt.getDouble("stormlearn");
			instance.storm_release = nbt.getDouble("storm_release");
			instance.stormlaser = nbt.getBoolean("stormlaser");
			instance.namikaze_release = nbt.getDouble("namikaze_release");
			instance.otsutsuki_release = nbt.getDouble("otsutsuki_release");
			instance.otsutsuki_tool = nbt.getDouble("otsutsuki_tool");
			instance.dojutsurinnegan = nbt.getString("dojutsurinnegan");
			instance.dojutsutenseigan = nbt.getString("dojutsutenseigan");
			instance.tenseigan = nbt.getBoolean("tenseigan");
			instance.tenseiganactivate = nbt.getBoolean("tenseiganactivate");
			instance.rinnegan = nbt.getBoolean("rinnegan");
			instance.rinneganactivate = nbt.getBoolean("rinneganactivate");
			instance.otsutsuki_path = nbt.getDouble("otsutsuki_path");
			instance.woodreleaselogic = nbt.getBoolean("woodreleaselogic");
			instance.woodtechnique = nbt.getDouble("woodtechnique");
			instance.woodlearn = nbt.getDouble("woodlearn");
			instance.wood_release = nbt.getDouble("wood_release");
			instance.otsutsuki_mangekyou = nbt.getBoolean("otsutsuki_mangekyou");
			instance.senju_release = nbt.getDouble("senju_release");
			instance.icereleaselogic = nbt.getBoolean("icereleaselogic");
			instance.icetechnique = nbt.getDouble("icetechnique");
			instance.icelearn = nbt.getDouble("icelearn");
			instance.ice_release = nbt.getDouble("ice_release");
			instance.ice_mirror = nbt.getBoolean("ice_mirror");
			instance.yuki_release = nbt.getDouble("yuki_release");
			instance.tenro_release = nbt.getDouble("tenro_release");
			instance.tenrolearn = nbt.getDouble("tenrolearn");
			instance.tenrotechnique = nbt.getDouble("tenrotechnique");
			instance.tenromode = nbt.getBoolean("tenromode");
			instance.izuno_release = nbt.getDouble("izuno_release");
			instance.izunolearn = nbt.getDouble("izunolearn");
			instance.izunotechnique = nbt.getDouble("izunotechnique");
			instance.izunochakramode = nbt.getBoolean("izunochakramode");
			instance.izunocat = nbt.getBoolean("izunocat");
			instance.calendar_calculator = nbt.getDouble("calendar_calculator");
			instance.gift = nbt.getDouble("gift");
			instance.giftcount = nbt.getDouble("giftcount");
			instance.christmas2022 = nbt.getBoolean("christmas2022");
			instance.shimura_active = nbt.getBoolean("shimura_active");
			instance.SharinganShimura = nbt.getBoolean("SharinganShimura");
			instance.aburametechnique = nbt.getDouble("aburametechnique");
			instance.aburamelearn = nbt.getDouble("aburamelearn");
			instance.aburame_release = nbt.getDouble("aburame_release");
			instance.sarutobitechnique = nbt.getDouble("sarutobitechnique");
			instance.sarutobilearn = nbt.getDouble("sarutobilearn");
			instance.sarutobirelease = nbt.getDouble("sarutobirelease");
			instance.hozukitechnique = nbt.getDouble("hozukitechnique");
			instance.hozukilearn = nbt.getDouble("hozukilearn");
			instance.hozukirelease = nbt.getDouble("hozukirelease");
			instance.tsuchigumotechnique = nbt.getDouble("tsuchigumotechnique");
			instance.tsuchigumolearn = nbt.getDouble("tsuchigumolearn");
			instance.tsuchigumorelease = nbt.getDouble("tsuchigumorelease");
			instance.waterblob = nbt.getBoolean("waterblob");
			instance.Great_Water_Arm = nbt.getBoolean("Great_Water_Arm");
			instance.bonereleaselogic = nbt.getBoolean("bonereleaselogic");
			instance.bonetechnique = nbt.getDouble("bonetechnique");
			instance.bonelearn = nbt.getDouble("bonelearn");
			instance.bone_release = nbt.getDouble("bone_release");
			instance.DanceOfTheLarch = nbt.getBoolean("DanceOfTheLarch");
			instance.kaguya_release = nbt.getDouble("kaguya_release");
			instance.hoshigaki_release = nbt.getDouble("hoshigaki_release");
			instance.fumatechnique = nbt.getDouble("fumatechnique");
			instance.fumalearn = nbt.getDouble("fumalearn");
			instance.fumarelease = nbt.getDouble("fumarelease");
			instance.magnet_coat = nbt.getDouble("magnet_coat");
			instance.Shadow1X = nbt.getDouble("Shadow1X");
			instance.Shadow2X = nbt.getDouble("Shadow2X");
			instance.Shadow1Z = nbt.getDouble("Shadow1Z");
			instance.Shadow2Z = nbt.getDouble("Shadow2Z");
			instance.NaraClanShadow = nbt.getBoolean("NaraClanShadow");
			instance.OriginalZ1 = nbt.getDouble("OriginalZ1");
			instance.OriginalX1 = nbt.getDouble("OriginalX1");
			instance.EightTrigramsPalmsRevolvingHeaven = nbt.getBoolean("EightTrigramsPalmsRevolvingHeaven");
			instance.InsectJarTechnique = nbt.getBoolean("InsectJarTechnique");
			instance.ShadowX1 = nbt.getDouble("ShadowX1");
			instance.ShadowX2 = nbt.getDouble("ShadowX2");
			instance.ShadowZ1 = nbt.getDouble("ShadowZ1");
			instance.ShadowZ2 = nbt.getDouble("ShadowZ2");
			instance.akimichitechnique = nbt.getDouble("akimichitechnique");
			instance.akimichilearn = nbt.getDouble("akimichilearn");
			instance.akimichirelease = nbt.getDouble("akimichirelease");
			instance.caloriecontrol = nbt.getDouble("caloriecontrol");
			instance.HumanBulletTank = nbt.getBoolean("HumanBulletTank");
			instance.ButterflyMode = nbt.getBoolean("ButterflyMode");
			instance.SpikedHumanBulletTank = nbt.getBoolean("SpikedHumanBulletTank");
			instance.zombiekillcount = nbt.getDouble("zombiekillcount");
			instance.pillagerkillcount = nbt.getDouble("pillagerkillcount");
			instance.typhoontechnique = nbt.getDouble("typhoontechnique");
			instance.typhoonlearn = nbt.getDouble("typhoonlearn");
			instance.typhoonrelease = nbt.getDouble("typhoonrelease");
			instance.typhoonreleaslogic = nbt.getBoolean("typhoonreleaslogic");
			instance.swiftlearn = nbt.getDouble("swiftlearn");
			instance.swiftrelease = nbt.getDouble("swiftrelease");
			instance.swiftreleaselogic = nbt.getBoolean("swiftreleaselogic");
			instance.steeltechnique = nbt.getDouble("steeltechnique");
			instance.steellearn = nbt.getDouble("steellearn");
			instance.steelrelease = nbt.getDouble("steelrelease");
			instance.steelreleaselogic = nbt.getBoolean("steelreleaselogic");
			instance.dusttechnique = nbt.getDouble("dusttechnique");
			instance.dustlearn = nbt.getDouble("dustlearn");
			instance.dustrelease = nbt.getDouble("dustrelease");
			instance.dustreleaselogic = nbt.getBoolean("dustreleaselogic");
			instance.boiltechnique = nbt.getDouble("boiltechnique");
			instance.boillearn = nbt.getDouble("boillearn");
			instance.boilrelease = nbt.getDouble("boilrelease");
			instance.boilreleaselogic = nbt.getBoolean("boilreleaselogic");
			instance.swiftmode = nbt.getBoolean("swiftmode");
			instance.UnrivaledStrength = nbt.getBoolean("UnrivaledStrength");
			instance.ImperviousArmor = nbt.getBoolean("ImperviousArmor");
			instance.WindMode = nbt.getBoolean("WindMode");
			instance.SmokeForm = nbt.getBoolean("SmokeForm");
			instance.ButterFlyModeColor = nbt.getString("ButterFlyModeColor");
			instance.HPBarfill = nbt.getDouble("HPBarfill");
			instance.ChakraBarfill = nbt.getDouble("ChakraBarfill");
			instance.DashCooldown = nbt.getBoolean("DashCooldown");
			instance.DashCooldownTicks = nbt.getDouble("DashCooldownTicks");
			instance.WPressed = nbt.getDouble("WPressed");
			instance.APressed = nbt.getDouble("APressed");
			instance.DPressed = nbt.getDouble("DPressed");
			instance.SPressed = nbt.getDouble("SPressed");
			instance.SpacePressed = nbt.getDouble("SpacePressed");
			instance.UpDashCooldown = nbt.getBoolean("UpDashCooldown");
			instance.UpDashCooldownTicks = nbt.getDouble("UpDashCooldownTicks");
			instance.SpaceHold = nbt.getBoolean("SpaceHold");
			instance.Dash = nbt.getBoolean("Dash");
			instance.DashReset = nbt.getDouble("DashReset");
			instance.WHold = nbt.getBoolean("WHold");
			instance.WaterWalk = nbt.getBoolean("WaterWalk");
			instance.WallClimb = nbt.getBoolean("WallClimb");
			instance.SusanoActive = nbt.getDouble("SusanoActive");
			instance.SusanoForms = nbt.getDouble("SusanoForms");
			instance.StorymodeCooldown = nbt.getDouble("StorymodeCooldown");
			instance.directionstorymode = nbt.getString("directionstorymode");
			instance.TrainingDummyHits = nbt.getDouble("TrainingDummyHits");
			instance.StoryModeGeninFight = nbt.getString("StoryModeGeninFight");
			instance.HeadbandSelect = nbt.getDouble("HeadbandSelect");
			instance.Kagutsuchi = nbt.getBoolean("Kagutsuchi");
			instance.AmaterasuSusano = nbt.getBoolean("AmaterasuSusano");
			instance.MangekyouSharinganRelease = nbt.getDouble("MangekyouSharinganRelease");
			instance.mangekyousharingansasukeamaterasurelease = nbt.getDouble("mangekyousharingansasukeamaterasurelease");
			instance.mangekyousharingansasukeamaterasulearn = nbt.getDouble("mangekyousharingansasukeamaterasulearn");
			instance.mangekyousharingansasukeamaterasutechnique = nbt.getDouble("mangekyousharingansasukeamaterasutechnique");
			instance.mangekyousharingansasukesusanorelease = nbt.getDouble("mangekyousharingansasukesusanorelease");
			instance.mangekyousharingansasukesusanolearn = nbt.getDouble("mangekyousharingansasukesusanolearn");
			instance.mangekyousharingansusanostage = nbt.getDouble("mangekyousharingansusanostage");
			instance.mangekyoushrainganitachiamaterasulearn = nbt.getDouble("mangekyoushrainganitachiamaterasulearn");
			instance.mangekyoushrainganitachisusanorelease = nbt.getDouble("mangekyoushrainganitachisusanorelease");
			instance.mangekyoushrainganitachisusanolearn = nbt.getDouble("mangekyoushrainganitachisusanolearn");
			instance.mangekyousharingankakashikamuilearn = nbt.getDouble("mangekyousharingankakashikamuilearn");
			instance.mangekyousharinganobitokamuirelease = nbt.getDouble("mangekyousharinganobitokamuirelease");
			instance.mangekyousharinganobitokamuilearn = nbt.getDouble("mangekyousharinganobitokamuilearn");
			instance.mangekyousharinganobitokamuitechnique = nbt.getDouble("mangekyousharinganobitokamuitechnique");
			instance.mangekyousharinganobitosusanorelease = nbt.getDouble("mangekyousharinganobitosusanorelease");
			instance.mangekyousharinganobitosusanolearn = nbt.getDouble("mangekyousharinganobitosusanolearn");
			instance.KamuiPhantomPhase = nbt.getBoolean("KamuiPhantomPhase");
			instance.Eternal_Mangekyou_Sharingan = nbt.getBoolean("Eternal_Mangekyou_Sharingan");
			instance.Eternal_Mangekyou_Sharingan_Sasuke = nbt.getBoolean("Eternal_Mangekyou_Sharingan_Sasuke");
			instance.Eternal_Mangekyou_Sharingan_Madara = nbt.getBoolean("Eternal_Mangekyou_Sharingan_Madara");
			instance.Mangekyou_Sharingan_Technique_Use = nbt.getDouble("Mangekyou_Sharingan_Technique_Use");
			instance.Mangekyou_Sharingan_Technique_Use_Max = nbt.getDouble("Mangekyou_Sharingan_Technique_Use_Max");
			instance.mangekyousharinganmadarasusanorelease = nbt.getDouble("mangekyousharinganmadarasusanorelease");
			instance.mangekyousharinganmadarasusanolearn = nbt.getDouble("mangekyousharinganmadarasusanolearn");
			instance.mangekyousharinganshisuisusanorelease = nbt.getDouble("mangekyousharinganshisuisusanorelease");
			instance.mangekyousharinganshisuisusanolearn = nbt.getDouble("mangekyousharinganshisuisusanolearn");
			instance.genjutsueffect = nbt.getString("genjutsueffect");
			instance.samehadamode = nbt.getDouble("samehadamode");
			instance.gunbaicopy = ItemStack.read(nbt.getCompound("gunbaicopy"));
			instance.LevelStatMaxChange = nbt.getDouble("LevelStatMaxChange");
			instance.inuzuka_mode = nbt.getDouble("inuzuka_mode");
		}
	}

	public static class PlayerVariables {
		public double A_Mission = 0;
		public boolean aburamereleaselogic = false;
		public boolean akimichireleaselogic = false;
		public boolean asumaquest = false;
		public double B_Mission = 0;
		public double BOSSLEVEL = 0;
		public double BOSSLEVELMAX = 1000.0;
		public boolean byakugan = false;
		public boolean byakuganactivate = false;
		public double C_Mission = 0;
		public double ChakraAmount = 0;
		public double ChakraMax = 0.0;
		public boolean chinoikereleaselogic = false;
		public double D_Mission = 0;
		public boolean deathgod = false;
		public String DojutsuSelectResize = "Sharingan";
		public double earth_release = 0;
		public double earth_technique = 0;
		public double earthlearn = 0;
		public boolean earthreleaselogic = false;
		public double Eyes_Height = 1.0;
		public double fire_release = 0;
		public double firelearn = 0;
		public boolean firereleaselogic = false;
		public double firetechnique = 0;
		public boolean fumareleaselogic = false;
		public double genjutsu = 0;
		public boolean gentlefist = false;
		public boolean hatakereleaselogic = false;
		public boolean healbite = false;
		public double Health = 0;
		public double HealthMax = 0;
		public boolean hoshigakireleaselogic = false;
		public boolean hozukireleaselogic = false;
		public double hyugalearn = 0.0;
		public double hyugarelease = 0;
		public boolean hyugareleaselogic = false;
		public double hyugatechnique = 0;
		public boolean iburireleaselogic = false;
		public boolean inuzukareleaselogic = false;
		public double IQ = 0;
		public boolean izanagi = false;
		public boolean izanagiuse = false;
		public boolean izunoreleaselogic = false;
		public boolean joinworld = false;
		public double jp = 0;
		public double jutsupower = 0.0;
		public double jutsupowerstat = 0;
		public boolean kaguyareleaselogic = false;
		public boolean kazekagereleaselogic = false;
		public double kenjutsu = 0;
		public boolean ketsuryugan = false;
		public boolean ketsuryuganactivate = false;
		public double kinjutsu = 0;
		public boolean kuramareleaselogic = false;
		public boolean leereleaselogic = false;
		public double LEVEL = 0.0;
		public double LEVELMAX = 1.0;
		public double LEVELMAXMINIGAME = 5.0;
		public double LEVELMINIGAME = 0;
		public double LEVELSTAT = 0.0;
		public double LEVELSTATMINIGAME = 0;
		public double lightning_release = 0;
		public double lightning_technique = 0.0;
		public double lightninglearn = 0;
		public boolean lightningreleaselogic = false;
		public boolean Mangekyou_Sharingan = false;
		public double maxhealth = 20.0;
		public double maxspeed = 0.1;
		public double medicine = 0;
		public double Mini_Game_Timer_Button = 0;
		public boolean namikazereleaselogic = false;
		public boolean narareleaselogic = false;
		public double NarutoTimerAwakening = 0;
		public double ninjutsu = 0;
		public boolean otsutsukireleaselogic = false;
		public double Pupils_Height = 1.0;
		public String rank = "Academy Student";
		public double S_Mission = 0;
		public boolean sarutobireleaselogic = false;
		public double selectclanrelease = 0;
		public double selectnaturerelease = 0;
		public double selectvillage = 0;
		public boolean senjureleaselogic = false;
		public double senjutsu = 0;
		public double SenjutsuChakraAmount = 0;
		public double SenjutsuChakraMax = 0;
		public boolean sharingan = false;
		public boolean sharinganactivate = false;
		public double sharinganlearn = 0.0;
		public double sharinganrelease = 0;
		public double sharingantechnique = 0.0;
		public boolean shikamaruquest = false;
		public boolean shimurareleaselogic = false;
		public double Shinobi_Murder_Count = 0;
		public double shurikenjutsu = 0;
		public double smokelearn = 0.0;
		public boolean smokereleaselogic = false;
		public double smoketechnique = 0;
		public double sp = 0;
		public double speed = 0;
		public double spusecount = 1.0;
		public double SS_Mission = 0;
		public double storymode = 0;
		public double summoning = 0;
		public double taijutsu = 0;
		public boolean tenroreleaselogic = false;
		public boolean tsuchigumoreleaselogic = false;
		public boolean uchihareleaselogic = false;
		public boolean uzumakichains = false;
		public double uzumakilearn = 0.0;
		public double uzumakirelease = 0;
		public boolean uzumakireleaselogic = false;
		public double uzumakitechnique = 0.0;
		public String village = "";
		public double water_release = 0;
		public double water_technique = 0;
		public double waterlearn = 0;
		public boolean waterreleaselogic = false;
		public double wind_release = 0;
		public double wind_technique = 0;
		public double windlearn = 0;
		public boolean windreleaselogic = false;
		public boolean yukireleaselogic = false;
		public boolean smokefist = false;
		public double smokerelease = 0;
		public boolean Chakra_Control = false;
		public String player_name = "\"\"";
		public String customjutsutype = "Ball";
		public String customjutsuspeed = "Slow";
		public String customjutsurelease = "Fire";
		public double customjutsuchakra = 100.0;
		public double customjutsujpcost = 0;
		public String customjutsu1name = "\"\"";
		public boolean customjutsucheckpricelogic = false;
		public double customjutsucheckpricefinal = 0;
		public boolean customjutsujpreadybuy = false;
		public boolean customjutsufire = false;
		public boolean customjutsuwind = false;
		public boolean customjutsulightning = false;
		public boolean customjutsuwater = false;
		public boolean customjutsuearth = false;
		public String customjutsutypesave = "\"\"";
		public String customjutsuspeedsave = "\"\"";
		public String customjutsureleasesave = "\"\"";
		public double customjutsuchakrasave = 0;
		public String customjutsutype1save = "\"\"";
		public String customjutsuspeed1save = "\"\"";
		public String customjutsurelease1save = "\"\"";
		public double customjutsuchakra1save = 0;
		public String jutsunamesave = "\"\"";
		public String jutsunamesave1 = "\"\"";
		public boolean customjutsu1learn = false;
		public boolean isshikidojutsu = false;
		public boolean isshikidojutsuactivate = false;
		public double sukunahikonasize = 0.1;
		public double isshikidojutsutechnique = 0.0;
		public double isshikidojutsulearn = 0.0;
		public double isshikidojutsurelease = 0;
		public boolean FollowAkamaru = true;
		public double inuzukatechnique = 0;
		public double inuzukalearn = 0.0;
		public boolean mangekyouletter = false;
		public double magnettechnique = 0;
		public boolean magnetreleaselogic = false;
		public double magnetlearn = 0;
		public boolean BoxDeity = false;
		public boolean Login_Dojutsu = false;
		public double voltic_technique = 0;
		public double volticlearn = 0.0;
		public String DojutsuSelect2 = "Default";
		public String DojutsuSelect3 = " ";
		public boolean MangekyouSharinganSasuke = false;
		public boolean MangekyouSharinganItachi = false;
		public boolean MangekyouSharinganMadara = false;
		public boolean MangekyouSharinganObito = false;
		public boolean MangekyouSharinganShisui = false;
		public boolean MangekyouSharinganActivate = false;
		public boolean MangekyouSharinganKakashi = false;
		public boolean SharinganKakashi = false;
		public double hatakelearn = 0;
		public double volticrelease = 0;
		public boolean BoxDojutsuSelect = false;
		public boolean VolticThomasCannonDamage = false;
		public boolean VolticMode = false;
		public double magnet_release = 0;
		public double lee_technique = 0;
		public double leelearn = 0;
		public double eight_gates = 0;
		public boolean deathgodcooldown = false;
		public double iburi_release = 0;
		public double inuzuka_release = 0;
		public boolean akamaru_summon = false;
		public double kazekage_release = 0;
		public boolean TheSirMarcus = false;
		public double furamingogan_technique = 0;
		public double furamingoganlearn = 0;
		public double furamingoganrelease = 0;
		public boolean TheSirMarcusDojutsuSelect = false;
		public boolean Furamingogan = false;
		public boolean furamingogan_jump = false;
		public double lee_release = 0;
		public double gateslee = 0;
		public boolean Gate8 = false;
		public double flyingthundergodkunaicount = 0;
		public double flyingthundergodkunaipos1x = 0;
		public double flyingthundergodkunaipos1y = 0;
		public double flyingthundergodkunaipos1z = 0;
		public double flyingthundergodkunaipos2x = 0;
		public double flyingthundergodkunaipos2y = 0;
		public double flyingthundergodkunaipos2z = 0;
		public double flyingthundergodkunaipos3x = 0;
		public double flyingthundergodkunaipos3y = 0;
		public double flyingthundergodkunaipos3z = 0;
		public double flyingthundergodkunaiteleportselect = 0;
		public boolean flyingthundergodkunaipos1logic = false;
		public boolean flyingthundergodkunaipos2logic = false;
		public boolean flyingthundergodkunaipos3logic = false;
		public double flyingthundergodkunaicount1 = 0;
		public double flyingthundergodkunaicount2 = 0;
		public double dojutsusize = 0;
		public String dojutsubyakugan = "\"\"";
		public String dojutsusharingan = "\"\"";
		public String dojutsuketsuryugan = "\"\"";
		public String dojutsums = "\"\"";
		public String dojutsuisshiki = "\"\"";
		public boolean PassingFang = false;
		public double stormtechnique = 0;
		public boolean stormreleaselogic = false;
		public double stormlearn = 0;
		public double storm_release = 0;
		public boolean stormlaser = false;
		public double namikaze_release = 0;
		public double otsutsuki_release = 0;
		public double otsutsuki_tool = 0;
		public String dojutsurinnegan = "\"\"";
		public String dojutsutenseigan = "\"\"";
		public boolean tenseigan = false;
		public boolean tenseiganactivate = false;
		public boolean rinnegan = false;
		public boolean rinneganactivate = false;
		public double otsutsuki_path = 0;
		public boolean woodreleaselogic = false;
		public double woodtechnique = 0;
		public double woodlearn = 0;
		public double wood_release = 0;
		public boolean otsutsuki_mangekyou = false;
		public double senju_release = 0;
		public boolean icereleaselogic = false;
		public double icetechnique = 0;
		public double icelearn = 0;
		public double ice_release = 0;
		public boolean ice_mirror = false;
		public double yuki_release = 0;
		public double tenro_release = 0;
		public double tenrolearn = 0;
		public double tenrotechnique = 0;
		public boolean tenromode = false;
		public double izuno_release = 0;
		public double izunolearn = 0;
		public double izunotechnique = 0;
		public boolean izunochakramode = false;
		public boolean izunocat = false;
		public double calendar_calculator = 0;
		public double gift = 0;
		public double giftcount = 0;
		public boolean christmas2022 = false;
		public boolean shimura_active = false;
		public boolean SharinganShimura = false;
		public double aburametechnique = 0;
		public double aburamelearn = 0;
		public double aburame_release = 0;
		public double sarutobitechnique = 0;
		public double sarutobilearn = 0;
		public double sarutobirelease = 0;
		public double hozukitechnique = 0;
		public double hozukilearn = 0;
		public double hozukirelease = 0;
		public double tsuchigumotechnique = 0;
		public double tsuchigumolearn = 0;
		public double tsuchigumorelease = 0;
		public boolean waterblob = false;
		public boolean Great_Water_Arm = false;
		public boolean bonereleaselogic = false;
		public double bonetechnique = 0;
		public double bonelearn = 0;
		public double bone_release = 0;
		public boolean DanceOfTheLarch = false;
		public double kaguya_release = 0;
		public double hoshigaki_release = 0;
		public double fumatechnique = 0;
		public double fumalearn = 0;
		public double fumarelease = 0;
		public double magnet_coat = 0;
		public double Shadow1X = 0;
		public double Shadow2X = 0;
		public double Shadow1Z = 0;
		public double Shadow2Z = 0;
		public boolean NaraClanShadow = false;
		public double OriginalZ1 = 0;
		public double OriginalX1 = 0;
		public boolean EightTrigramsPalmsRevolvingHeaven = false;
		public boolean InsectJarTechnique = false;
		public double ShadowX1 = 0;
		public double ShadowX2 = 0;
		public double ShadowZ1 = 0;
		public double ShadowZ2 = 0;
		public double akimichitechnique = 0;
		public double akimichilearn = 0;
		public double akimichirelease = 0;
		public double caloriecontrol = 1.0;
		public boolean HumanBulletTank = false;
		public boolean ButterflyMode = false;
		public boolean SpikedHumanBulletTank = false;
		public double zombiekillcount = 0;
		public double pillagerkillcount = 0;
		public double typhoontechnique = 0;
		public double typhoonlearn = 0;
		public double typhoonrelease = 0;
		public boolean typhoonreleaslogic = false;
		public double swiftlearn = 0;
		public double swiftrelease = 0;
		public boolean swiftreleaselogic = false;
		public double steeltechnique = 0;
		public double steellearn = 0;
		public double steelrelease = 0;
		public boolean steelreleaselogic = false;
		public double dusttechnique = 0;
		public double dustlearn = 0;
		public double dustrelease = 0;
		public boolean dustreleaselogic = false;
		public double boiltechnique = 0;
		public double boillearn = 0;
		public double boilrelease = 0;
		public boolean boilreleaselogic = false;
		public boolean swiftmode = false;
		public boolean UnrivaledStrength = false;
		public boolean ImperviousArmor = false;
		public boolean WindMode = false;
		public boolean SmokeForm = false;
		public String ButterFlyModeColor = "\"\"";
		public double HPBarfill = 0;
		public double ChakraBarfill = 0;
		public boolean DashCooldown = false;
		public double DashCooldownTicks = 0;
		public double WPressed = 0;
		public double APressed = 0;
		public double DPressed = 0;
		public double SPressed = 0;
		public double SpacePressed = 0;
		public boolean UpDashCooldown = false;
		public double UpDashCooldownTicks = 0;
		public boolean SpaceHold = false;
		public boolean Dash = false;
		public double DashReset = 0;
		public boolean WHold = false;
		public boolean WaterWalk = false;
		public boolean WallClimb = false;
		public double SusanoActive = 0;
		public double SusanoForms = 0;
		public double StorymodeCooldown = 0;
		public String directionstorymode = "\"\"";
		public double TrainingDummyHits = 0;
		public String StoryModeGeninFight = " ";
		public double HeadbandSelect = 0;
		public boolean Kagutsuchi = false;
		public boolean AmaterasuSusano = false;
		public double MangekyouSharinganRelease = 0;
		public double mangekyousharingansasukeamaterasurelease = 0;
		public double mangekyousharingansasukeamaterasulearn = 0;
		public double mangekyousharingansasukeamaterasutechnique = 0;
		public double mangekyousharingansasukesusanorelease = 0;
		public double mangekyousharingansasukesusanolearn = 0;
		public double mangekyousharingansusanostage = 0;
		public double mangekyoushrainganitachiamaterasulearn = 0;
		public double mangekyoushrainganitachisusanorelease = 0;
		public double mangekyoushrainganitachisusanolearn = 0;
		public double mangekyousharingankakashikamuilearn = 0;
		public double mangekyousharinganobitokamuirelease = 0;
		public double mangekyousharinganobitokamuilearn = 0;
		public double mangekyousharinganobitokamuitechnique = 0;
		public double mangekyousharinganobitosusanorelease = 0;
		public double mangekyousharinganobitosusanolearn = 0;
		public boolean KamuiPhantomPhase = false;
		public boolean Eternal_Mangekyou_Sharingan = false;
		public boolean Eternal_Mangekyou_Sharingan_Sasuke = false;
		public boolean Eternal_Mangekyou_Sharingan_Madara = false;
		public double Mangekyou_Sharingan_Technique_Use = 0;
		public double Mangekyou_Sharingan_Technique_Use_Max = 0;
		public double mangekyousharinganmadarasusanorelease = 0;
		public double mangekyousharinganmadarasusanolearn = 0;
		public double mangekyousharinganshisuisusanorelease = 0;
		public double mangekyousharinganshisuisusanolearn = 0;
		public String genjutsueffect = "\"\"";
		public double samehadamode = 0;
		public ItemStack gunbaicopy = ItemStack.EMPTY;
		public double LevelStatMaxChange = 100.0;
		public double inuzuka_mode = 0;

		/** Queues a sync to the owning client; sent once at the end of the current server tick. */
		public void syncPlayerVariables(Entity entity) {
			if (entity instanceof ServerPlayerEntity)
				PENDING_SYNC.add((ServerPlayerEntity) entity);
		}
	}

	@SubscribeEvent
	public void onPlayerLoggedInSyncPlayerVariables(PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.getPlayer().world.isRemote())
			get(event.getPlayer())
					.syncPlayerVariables(event.getPlayer());
	}

	@SubscribeEvent
	public void onPlayerRespawnedSyncPlayerVariables(PlayerEvent.PlayerRespawnEvent event) {
		if (!event.getPlayer().world.isRemote())
			get(event.getPlayer())
					.syncPlayerVariables(event.getPlayer());
	}

	@SubscribeEvent
	public void onPlayerChangedDimensionSyncPlayerVariables(PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.getPlayer().world.isRemote())
			get(event.getPlayer())
					.syncPlayerVariables(event.getPlayer());
	}

	@SubscribeEvent
	public void clonePlayer(PlayerEvent.Clone event) {
		PlayerVariables original = event.getOriginal().getCapability(PLAYER_VARIABLES_CAPABILITY, null).orElse(null);
		PlayerVariables clone = event.getEntity().getCapability(PLAYER_VARIABLES_CAPABILITY, null).orElse(null);
		if (original != null && clone != null)
			STORAGE.readNBT(null, clone, null, STORAGE.writeNBT(null, original, null));
	}

	/** Players whose variables changed this tick; flushed once at the end of the server tick. */
	private static final Set<ServerPlayerEntity> PENDING_SYNC = new LinkedHashSet<>();

	@SubscribeEvent
	public void flushPendingSyncs(TickEvent.ServerTickEvent event) {
		if (event.phase != TickEvent.Phase.END || PENDING_SYNC.isEmpty())
			return;
		for (ServerPlayerEntity player : PENDING_SYNC) {
			if (!player.hasDisconnected())
				NarutoShippudenMod.PACKET_HANDLER.send(PacketDistributor.PLAYER.with(() -> player), new PlayerVariablesSyncMessage(get(player)));
		}
		PENDING_SYNC.clear();
	}

	public static class PlayerVariablesSyncMessage {
		private final CompoundNBT data;

		public PlayerVariablesSyncMessage(PacketBuffer buffer) {
			this.data = buffer.readCompoundTag();
		}

		public PlayerVariablesSyncMessage(PlayerVariables data) {
			this.data = (CompoundNBT) STORAGE.writeNBT(null, data, null);
		}

		public static void buffer(PlayerVariablesSyncMessage message, PacketBuffer buffer) {
			buffer.writeCompoundTag(message.data);
		}

		public static void handler(PlayerVariablesSyncMessage message, Supplier<NetworkEvent.Context> contextSupplier) {
			NetworkEvent.Context context = contextSupplier.get();
			context.enqueueWork(() -> {
				if (!context.getDirection().getReceptionSide().isServer())
					Minecraft.getInstance().player.getCapability(PLAYER_VARIABLES_CAPABILITY, null)
							.ifPresent(variables -> STORAGE.readNBT(null, variables, null, message.data));
			});
			context.setPacketHandled(true);
		}
	}
}
