package net.mcreator.narutoshippudenmod.client;

import net.mcreator.narutoshippudenmod.entity.renderer.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.EntityRenderersEvent;
import net.neoforged.neoforge.client.extensions.common.RegisterClientExtensionsEvent;
import net.neoforged.neoforge.client.event.RegisterMenuScreensEvent;
import net.neoforged.neoforge.client.event.RegisterParticleProvidersEvent;
import net.mcreator.narutoshippudenmod.gui.*;
import net.mcreator.narutoshippudenmod.gui.CheatGuis.*;
import net.mcreator.narutoshippudenmod.gui.CheatScreens.*;
import net.mcreator.narutoshippudenmod.gui.InfoCardGuis.*;
import net.mcreator.narutoshippudenmod.gui.InfoCardScreens.*;
import net.mcreator.narutoshippudenmod.gui.JutsuCreationGuis.*;
import net.mcreator.narutoshippudenmod.gui.JutsuCreationScreens.*;
import net.mcreator.narutoshippudenmod.gui.MiscGuis.*;
import net.mcreator.narutoshippudenmod.gui.MiscScreens.*;

/** Client-side registration: entity renderers, model layers and item extensions. */
@EventBusSubscriber(modid = "naruto_shippuden", value = Dist.CLIENT)
public final class ModClient {
	private ModClient() {
	}

	@SubscribeEvent
	public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
		JutsuRenderers.ButterflyModeRenderer.registerRenderers(event);
		JutsuRenderers.CatChakraModeRenderer.registerRenderers(event);
		JutsuRenderers.CatChakraModeSneakRenderer.registerRenderers(event);
		JutsuRenderers.DanceOfTheLarchRenderer.registerRenderers(event);
		JutsuRenderers.DanceoftheLarchSneakRenderer.registerRenderers(event);
		JutsuRenderers.DeadDemonConsumingSealRenderer.registerRenderers(event);
		JutsuRenderers.DisruptionCubeRenderer.registerRenderers(event);
		JutsuRenderers.DrowningWaterBlobTechniqueEntityRenderer.registerRenderers(event);
		JutsuRenderers.DrowningWaterBlobTechniqueEntitySneakRenderer.registerRenderers(event);
		JutsuRenderers.EightTrigramsPalmsRevolvingHeavenRenderer.registerRenderers(event);
		JutsuRenderers.EightTrigramsSixtyFourPalmsRenderer.registerRenderers(event);
		JutsuRenderers.FangRenderer.registerRenderers(event);
		JutsuRenderers.FlyingThunderGodKunaiEntityRenderer.registerRenderers(event);
		JutsuRenderers.HumanBulletTankRenderer.registerRenderers(event);
		JutsuRenderers.IceMirrorRenderer.registerRenderers(event);
		JutsuRenderers.IceSpearRenderer.registerRenderers(event);
		JutsuRenderers.InsectJarTechniqueRenderer.registerRenderers(event);
		JutsuRenderers.MagnetCoatRenderer.registerRenderers(event);
		JutsuRenderers.MagnetCoatSneakRenderer.registerRenderers(event);
		JutsuRenderers.MagnetHandsRenderer.registerRenderers(event);
		JutsuRenderers.MagnetHandsSneakRenderer.registerRenderers(event);
		JutsuRenderers.MagnetWingsRenderer.registerRenderers(event);
		JutsuRenderers.RunningFireRenderer.registerRenderers(event);
		JutsuRenderers.ShadowCloneRenderer.registerRenderers(event);
		JutsuRenderers.ShadowImitationEntity2Renderer.registerRenderers(event);
		JutsuRenderers.ShadowImitationEntityRenderer.registerRenderers(event);
		JutsuRenderers.ShadowImitationFieldTechniqueRenderer.registerRenderers(event);
		JutsuRenderers.SpikedHumanBulletTankRenderer.registerRenderers(event);
		NpcRenderers.AsumaRenderer.registerRenderers(event);
		NpcRenderers.EarthGolemShinobiRenderer.registerRenderers(event);
		NpcRenderers.HiddenCloudShinobiRenderer.registerRenderers(event);
		NpcRenderers.HiddenLeafShinobiRenderer.registerRenderers(event);
		NpcRenderers.HiddenMistShinobiRenderer.registerRenderers(event);
		NpcRenderers.HiddenSandShinobiRenderer.registerRenderers(event);
		NpcRenderers.HiddenStoneShinobiRenderer.registerRenderers(event);
		NpcRenderers.IrukaSenseiCloneRenderer.registerRenderers(event);
		NpcRenderers.IrukaSenseiRenderer.registerRenderers(event);
		NpcRenderers.ShikamaruRenderer.registerRenderers(event);
		NpcRenderers.TrainingDummyRenderer.registerRenderers(event);
		ProjectileRenderers.AmaterasuFlameRenderer.registerRenderers(event);
		ProjectileRenderers.BlackIceDragonRenderer.registerRenderers(event);
		ProjectileRenderers.ChidoriSenbonRenderer.registerRenderers(event);
		ProjectileRenderers.CoercionSharinganRenderer.registerRenderers(event);
		ProjectileRenderers.DemonicIllusionShacklingStakesTechniqueRenderer.registerRenderers(event);
		ProjectileRenderers.DrowningWaterBlobTechniqueRenderer.registerRenderers(event);
		ProjectileRenderers.EarthBallRenderer.registerRenderers(event);
		ProjectileRenderers.EarthDiskRenderer.registerRenderers(event);
		ProjectileRenderers.EarthSpearRenderer.registerRenderers(event);
		ProjectileRenderers.EarthWaveRenderer.registerRenderers(event);
		ProjectileRenderers.ExplosiveKunaiBulletRenderer.registerRenderers(event);
		ProjectileRenderers.FireBallRenderer.registerRenderers(event);
		ProjectileRenderers.FireDiskRenderer.registerRenderers(event);
		ProjectileRenderers.FireDragonFlameBulletRenderer.registerRenderers(event);
		ProjectileRenderers.FireWaveRenderer.registerRenderers(event);
		ProjectileRenderers.FlyingThunderGodKunaiBulletRenderer.registerRenderers(event);
		ProjectileRenderers.FumaShurikenBulletRenderer.registerRenderers(event);
		ProjectileRenderers.FumaShurikenClanRenderer.registerRenderers(event);
		ProjectileRenderers.FuramingoganBeamRenderer.registerRenderers(event);
		ProjectileRenderers.FurykickRenderer.registerRenderers(event);
		ProjectileRenderers.GreatFireDragonRenderer.registerRenderers(event);
		ProjectileRenderers.GreatFireballRenderer.registerRenderers(event);
		ProjectileRenderers.InsectBogRenderer.registerRenderers(event);
		ProjectileRenderers.IronSandBulletRenderer.registerRenderers(event);
		ProjectileRenderers.KunaiBulletRenderer.registerRenderers(event);
		ProjectileRenderers.LaserCircusRenderer.registerRenderers(event);
		ProjectileRenderers.LightningBallCustomRenderer.registerRenderers(event);
		ProjectileRenderers.LightningBallRenderer.registerRenderers(event);
		ProjectileRenderers.LightningDiskRenderer.registerRenderers(event);
		ProjectileRenderers.LightningWaveRenderer.registerRenderers(event);
		ProjectileRenderers.MirrorRenderer.registerRenderers(event);
		ProjectileRenderers.NeedleSenbonRenderer.registerRenderers(event);
		ProjectileRenderers.NuibariBulletRenderer.registerRenderers(event);
		ProjectileRenderers.PhoenixFlowerJutsuRenderer.registerRenderers(event);
		ProjectileRenderers.PoisonKunaiBulletRenderer.registerRenderers(event);
		ProjectileRenderers.RasenshurikenRenderer.registerRenderers(event);
		ProjectileRenderers.ShurikenBulletRenderer.registerRenderers(event);
		ProjectileRenderers.ShurikenClanRenderer.registerRenderers(event);
		ProjectileRenderers.SmokeGunRenderer.registerRenderers(event);
		ProjectileRenderers.SteelProjectileRenderer.registerRenderers(event);
		ProjectileRenderers.TailedBeastBombRenderer.registerRenderers(event);
		ProjectileRenderers.ToroiUniqueFumaShurikenBulletRenderer.registerRenderers(event);
		ProjectileRenderers.ToroiUniqueFumaShurikenClanRenderer.registerRenderers(event);
		ProjectileRenderers.TreeBindRenderer.registerRenderers(event);
		ProjectileRenderers.UzumakiChainRenderer.registerRenderers(event);
		ProjectileRenderers.VacuumSphereRenderer.registerRenderers(event);
		ProjectileRenderers.WaterBallRenderer.registerRenderers(event);
		ProjectileRenderers.WaterDiskRenderer.registerRenderers(event);
		ProjectileRenderers.WaterDragonRenderer.registerRenderers(event);
		ProjectileRenderers.WaterGunRenderer.registerRenderers(event);
		ProjectileRenderers.WaterSharkBulletRenderer.registerRenderers(event);
		ProjectileRenderers.WaterWaveRenderer.registerRenderers(event);
		ProjectileRenderers.WindBallRenderer.registerRenderers(event);
		ProjectileRenderers.WindDiskRenderer.registerRenderers(event);
		ProjectileRenderers.WindWaveRenderer.registerRenderers(event);
		ProjectileRenderers.WoodDragonRenderer.registerRenderers(event);
		SummonRenderers.AkamaruRenderer.registerRenderers(event);
		SummonRenderers.CrowRenderer.registerRenderers(event);
		SummonRenderers.EarthGolemRenderer.registerRenderers(event);
		SummonRenderers.KirinRenderer.registerRenderers(event);
		SummonRenderers.KuramaRenderer.registerRenderers(event);
		SummonRenderers.MonsterCatRenderer.registerRenderers(event);
		SummonRenderers.ThreeHeadAkamaruRenderer.registerRenderers(event);
		SummonRenderers.TwoHeadAkamaruRenderer.registerRenderers(event);
		SummonRenderers.WolfRenderer.registerRenderers(event);
		SummonRenderers.WoodGolemRenderer.registerRenderers(event);
		SusanoRenderers.ArmoredSusanoMadaraRenderer.registerRenderers(event);
		SusanoRenderers.ArmoredSusanoSasukeRenderer.registerRenderers(event);
		SusanoRenderers.ArmoredSusanoShisuiRenderer.registerRenderers(event);
		SusanoRenderers.HumanoidSusanoItachiRenderer.registerRenderers(event);
		SusanoRenderers.HumanoidSusanoMadaraRenderer.registerRenderers(event);
		SusanoRenderers.HumanoidSusanoObitoRenderer.registerRenderers(event);
		SusanoRenderers.HumanoidSusanoSasukeRenderer.registerRenderers(event);
		SusanoRenderers.HumanoidSusanoShisuiRenderer.registerRenderers(event);
		SusanoRenderers.RibcageSusanoRenderer.registerRenderers(event);
		SusanoRenderers.SkeletonSusanoItachiRenderer.registerRenderers(event);
		SusanoRenderers.SkeletonSusanoMadaraRenderer.registerRenderers(event);
		SusanoRenderers.SkeletonSusanoObitoRenderer.registerRenderers(event);
		SusanoRenderers.SkeletonSusanoSasukeRenderer.registerRenderers(event);
		SusanoRenderers.SkeletonSusanoShisuiRenderer.registerRenderers(event);
	}

	@SubscribeEvent
	public static void registerLayers(EntityRenderersEvent.RegisterLayerDefinitions event) {
		JutsuRenderers.ButterflyModeRenderer.registerLayers(event);
		JutsuRenderers.CatChakraModeRenderer.registerLayers(event);
		JutsuRenderers.CatChakraModeSneakRenderer.registerLayers(event);
		JutsuRenderers.DanceOfTheLarchRenderer.registerLayers(event);
		JutsuRenderers.DanceoftheLarchSneakRenderer.registerLayers(event);
		JutsuRenderers.DeadDemonConsumingSealRenderer.registerLayers(event);
		JutsuRenderers.DisruptionCubeRenderer.registerLayers(event);
		JutsuRenderers.DrowningWaterBlobTechniqueEntityRenderer.registerLayers(event);
		JutsuRenderers.DrowningWaterBlobTechniqueEntitySneakRenderer.registerLayers(event);
		JutsuRenderers.EightTrigramsPalmsRevolvingHeavenRenderer.registerLayers(event);
		JutsuRenderers.EightTrigramsSixtyFourPalmsRenderer.registerLayers(event);
		JutsuRenderers.FangRenderer.registerLayers(event);
		JutsuRenderers.FlyingThunderGodKunaiEntityRenderer.registerLayers(event);
		JutsuRenderers.HumanBulletTankRenderer.registerLayers(event);
		JutsuRenderers.IceMirrorRenderer.registerLayers(event);
		JutsuRenderers.IceSpearRenderer.registerLayers(event);
		JutsuRenderers.InsectJarTechniqueRenderer.registerLayers(event);
		JutsuRenderers.MagnetCoatRenderer.registerLayers(event);
		JutsuRenderers.MagnetCoatSneakRenderer.registerLayers(event);
		JutsuRenderers.MagnetHandsRenderer.registerLayers(event);
		JutsuRenderers.MagnetHandsSneakRenderer.registerLayers(event);
		JutsuRenderers.MagnetWingsRenderer.registerLayers(event);
		JutsuRenderers.RunningFireRenderer.registerLayers(event);
		JutsuRenderers.ShadowCloneRenderer.registerLayers(event);
		JutsuRenderers.ShadowImitationEntity2Renderer.registerLayers(event);
		JutsuRenderers.ShadowImitationEntityRenderer.registerLayers(event);
		JutsuRenderers.ShadowImitationFieldTechniqueRenderer.registerLayers(event);
		JutsuRenderers.SpikedHumanBulletTankRenderer.registerLayers(event);
		NpcRenderers.AsumaRenderer.registerLayers(event);
		NpcRenderers.EarthGolemShinobiRenderer.registerLayers(event);
		NpcRenderers.HiddenCloudShinobiRenderer.registerLayers(event);
		NpcRenderers.HiddenLeafShinobiRenderer.registerLayers(event);
		NpcRenderers.HiddenMistShinobiRenderer.registerLayers(event);
		NpcRenderers.HiddenSandShinobiRenderer.registerLayers(event);
		NpcRenderers.HiddenStoneShinobiRenderer.registerLayers(event);
		NpcRenderers.IrukaSenseiCloneRenderer.registerLayers(event);
		NpcRenderers.IrukaSenseiRenderer.registerLayers(event);
		NpcRenderers.ShikamaruRenderer.registerLayers(event);
		NpcRenderers.TrainingDummyRenderer.registerLayers(event);
		ProjectileRenderers.AmaterasuFlameRenderer.registerLayers(event);
		ProjectileRenderers.BlackIceDragonRenderer.registerLayers(event);
		ProjectileRenderers.ChidoriSenbonRenderer.registerLayers(event);
		ProjectileRenderers.CoercionSharinganRenderer.registerLayers(event);
		ProjectileRenderers.DemonicIllusionShacklingStakesTechniqueRenderer.registerLayers(event);
		ProjectileRenderers.DrowningWaterBlobTechniqueRenderer.registerLayers(event);
		ProjectileRenderers.EarthBallRenderer.registerLayers(event);
		ProjectileRenderers.EarthDiskRenderer.registerLayers(event);
		ProjectileRenderers.EarthSpearRenderer.registerLayers(event);
		ProjectileRenderers.EarthWaveRenderer.registerLayers(event);
		ProjectileRenderers.ExplosiveKunaiBulletRenderer.registerLayers(event);
		ProjectileRenderers.FireBallRenderer.registerLayers(event);
		ProjectileRenderers.FireDiskRenderer.registerLayers(event);
		ProjectileRenderers.FireDragonFlameBulletRenderer.registerLayers(event);
		ProjectileRenderers.FireWaveRenderer.registerLayers(event);
		ProjectileRenderers.FlyingThunderGodKunaiBulletRenderer.registerLayers(event);
		ProjectileRenderers.FumaShurikenBulletRenderer.registerLayers(event);
		ProjectileRenderers.FumaShurikenClanRenderer.registerLayers(event);
		ProjectileRenderers.FuramingoganBeamRenderer.registerLayers(event);
		ProjectileRenderers.FurykickRenderer.registerLayers(event);
		ProjectileRenderers.GreatFireDragonRenderer.registerLayers(event);
		ProjectileRenderers.GreatFireballRenderer.registerLayers(event);
		ProjectileRenderers.InsectBogRenderer.registerLayers(event);
		ProjectileRenderers.IronSandBulletRenderer.registerLayers(event);
		ProjectileRenderers.KunaiBulletRenderer.registerLayers(event);
		ProjectileRenderers.LaserCircusRenderer.registerLayers(event);
		ProjectileRenderers.LightningBallCustomRenderer.registerLayers(event);
		ProjectileRenderers.LightningBallRenderer.registerLayers(event);
		ProjectileRenderers.LightningDiskRenderer.registerLayers(event);
		ProjectileRenderers.LightningWaveRenderer.registerLayers(event);
		ProjectileRenderers.MirrorRenderer.registerLayers(event);
		ProjectileRenderers.NeedleSenbonRenderer.registerLayers(event);
		ProjectileRenderers.NuibariBulletRenderer.registerLayers(event);
		ProjectileRenderers.PhoenixFlowerJutsuRenderer.registerLayers(event);
		ProjectileRenderers.PoisonKunaiBulletRenderer.registerLayers(event);
		ProjectileRenderers.RasenshurikenRenderer.registerLayers(event);
		ProjectileRenderers.ShurikenBulletRenderer.registerLayers(event);
		ProjectileRenderers.ShurikenClanRenderer.registerLayers(event);
		ProjectileRenderers.SmokeGunRenderer.registerLayers(event);
		ProjectileRenderers.SteelProjectileRenderer.registerLayers(event);
		ProjectileRenderers.TailedBeastBombRenderer.registerLayers(event);
		ProjectileRenderers.ToroiUniqueFumaShurikenBulletRenderer.registerLayers(event);
		ProjectileRenderers.ToroiUniqueFumaShurikenClanRenderer.registerLayers(event);
		ProjectileRenderers.TreeBindRenderer.registerLayers(event);
		ProjectileRenderers.UzumakiChainRenderer.registerLayers(event);
		ProjectileRenderers.VacuumSphereRenderer.registerLayers(event);
		ProjectileRenderers.WaterBallRenderer.registerLayers(event);
		ProjectileRenderers.WaterDiskRenderer.registerLayers(event);
		ProjectileRenderers.WaterDragonRenderer.registerLayers(event);
		ProjectileRenderers.WaterGunRenderer.registerLayers(event);
		ProjectileRenderers.WaterSharkBulletRenderer.registerLayers(event);
		ProjectileRenderers.WaterWaveRenderer.registerLayers(event);
		ProjectileRenderers.WindBallRenderer.registerLayers(event);
		ProjectileRenderers.WindDiskRenderer.registerLayers(event);
		ProjectileRenderers.WindWaveRenderer.registerLayers(event);
		ProjectileRenderers.WoodDragonRenderer.registerLayers(event);
		SummonRenderers.AkamaruRenderer.registerLayers(event);
		SummonRenderers.CrowRenderer.registerLayers(event);
		SummonRenderers.EarthGolemRenderer.registerLayers(event);
		SummonRenderers.KirinRenderer.registerLayers(event);
		SummonRenderers.KuramaRenderer.registerLayers(event);
		SummonRenderers.MonsterCatRenderer.registerLayers(event);
		SummonRenderers.ThreeHeadAkamaruRenderer.registerLayers(event);
		SummonRenderers.TwoHeadAkamaruRenderer.registerLayers(event);
		SummonRenderers.WolfRenderer.registerLayers(event);
		SummonRenderers.WoodGolemRenderer.registerLayers(event);
		SusanoRenderers.ArmoredSusanoMadaraRenderer.registerLayers(event);
		SusanoRenderers.ArmoredSusanoSasukeRenderer.registerLayers(event);
		SusanoRenderers.ArmoredSusanoShisuiRenderer.registerLayers(event);
		SusanoRenderers.HumanoidSusanoItachiRenderer.registerLayers(event);
		SusanoRenderers.HumanoidSusanoMadaraRenderer.registerLayers(event);
		SusanoRenderers.HumanoidSusanoObitoRenderer.registerLayers(event);
		SusanoRenderers.HumanoidSusanoSasukeRenderer.registerLayers(event);
		SusanoRenderers.HumanoidSusanoShisuiRenderer.registerLayers(event);
		SusanoRenderers.RibcageSusanoRenderer.registerLayers(event);
		SusanoRenderers.SkeletonSusanoItachiRenderer.registerLayers(event);
		SusanoRenderers.SkeletonSusanoMadaraRenderer.registerLayers(event);
		SusanoRenderers.SkeletonSusanoObitoRenderer.registerLayers(event);
		SusanoRenderers.SkeletonSusanoSasukeRenderer.registerLayers(event);
		SusanoRenderers.SkeletonSusanoShisuiRenderer.registerLayers(event);
		ArmorModels.registerLayers(event);
	}

	@SubscribeEvent
	public static void registerParticles(RegisterParticleProvidersEvent event) {
		ModParticleProviders.register(event);
	}

	@SubscribeEvent
	public static void registerScreens(RegisterMenuScreensEvent event) {
		event.register(InfoCardDojutsuGui.containerType, InfoCardDojutsuGuiWindow::new);
		event.register(InfoCardGui.containerType, InfoCardGuiWindow::new);
		event.register(InfoCardMiniGameGui.containerType, InfoCardMiniGameGuiWindow::new);
		event.register(InfoCardMissionsGui.containerType, InfoCardMissionsGuiWindow::new);
		event.register(InfoCardUpgradeGui.containerType, InfoCardUpgradeGuiWindow::new);
		event.register(StatSelectGui.containerType, StatSelectGuiWindow::new);
		event.register(CreateJutsuGUI2Gui.containerType, CreateJutsuGUI2GuiWindow::new);
		event.register(CreateJutsuGUIGui.containerType, CreateJutsuGUIGuiWindow::new);
		event.register(MangekyouSharinganCheatGui.containerType, MangekyouSharinganCheatGuiWindow::new);
		event.register(NarutoShippudenCheatDojutsuGUIGui.containerType, NarutoShippudenCheatDojutsuGUIGuiWindow::new);
		event.register(NarutoShippudenCheatGUIGui.containerType, NarutoShippudenCheatGUIGuiWindow::new);
		event.register(NarutoShippudenCheatKekkeiGenkaiGUIGui.containerType, NarutoShippudenCheatKekkeiGenkaiGUIGuiWindow::new);
		event.register(PasswordGUIDojutsuGui.containerType, PasswordGUIDojutsuGuiWindow::new);
		event.register(AdventCalendarGUIGui.containerType, AdventCalendarGUIGuiWindow::new);
		event.register(GeninHeadbandSelectGui.containerType, GeninHeadbandSelectGuiWindow::new);
		event.register(PatreonKitGui.containerType, PatreonKitGuiWindow::new);
	}

	@SubscribeEvent
	public static void registerExtensions(RegisterClientExtensionsEvent event) {
		ArmorModels.registerExtensions(event);
	}
}
